// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "01G0J1EXE7AXZ2C93K61WBPYEH"
 *     }
 */
export interface EscalationsV2ShowRequest {
    /** Unique ID of the escalation */
    id: string;
}
