// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *         skip_step_upgrades: false
 *     }
 */
export interface WorkflowsV2ShowWorkflowRequest {
    /** Unique identifier for the workflow */
    id: string;
    /** Skips workflow step upgrades, when the parameters for an existing workflow step change */
    skip_step_upgrades?: boolean;
}
