// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../../../../index.js";

/**
 * @example
 *     {
 *         annotations: {
 *             "incident.io/terraform/version": "3.0.0"
 *         },
 *         condition_groups: [{
 *                 conditions: [{
 *                         operation: "one_of",
 *                         param_bindings: [{
 *                                 array_value: [{
 *                                         literal: "SEV123",
 *                                         reference: "incident.severity"
 *                                     }],
 *                                 value: {
 *                                     literal: "SEV123",
 *                                     reference: "incident.severity"
 *                                 }
 *                             }],
 *                         subject: "incident.severity"
 *                     }]
 *             }],
 *         continue_on_step_error: true,
 *         delay: {
 *             conditions_apply_over_delay: false,
 *             for_seconds: 60
 *         },
 *         expressions: [{
 *                 else_branch: {
 *                     result: {
 *                         array_value: [{
 *                                 literal: "SEV123",
 *                                 reference: "incident.severity"
 *                             }],
 *                         value: {
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }
 *                     }
 *                 },
 *                 label: "Team Slack channel",
 *                 operations: [{
 *                         branches: {
 *                             branches: [{
 *                                     condition_groups: [{
 *                                             conditions: [{
 *                                                     operation: "one_of",
 *                                                     param_bindings: [{
 *                                                             array_value: [{
 *                                                                     literal: "SEV123",
 *                                                                     reference: "incident.severity"
 *                                                                 }],
 *                                                             value: {
 *                                                                 literal: "SEV123",
 *                                                                 reference: "incident.severity"
 *                                                             }
 *                                                         }],
 *                                                     subject: "incident.severity"
 *                                                 }]
 *                                         }],
 *                                     result: {
 *                                         array_value: [{
 *                                                 literal: "SEV123",
 *                                                 reference: "incident.severity"
 *                                             }],
 *                                         value: {
 *                                             literal: "SEV123",
 *                                             reference: "incident.severity"
 *                                         }
 *                                     }
 *                                 }],
 *                             returns: {
 *                                 array: true,
 *                                 type: "IncidentStatus"
 *                             }
 *                         },
 *                         concatenate: {
 *                             reference: "catalog_attribute[\"01FCNDV6P870EA6S7TK1DSYD5H\"]"
 *                         },
 *                         filter: {
 *                             condition_groups: [{
 *                                     conditions: [{
 *                                             operation: "one_of",
 *                                             param_bindings: [{
 *                                                     array_value: [{
 *                                                             literal: "SEV123",
 *                                                             reference: "incident.severity"
 *                                                         }],
 *                                                     value: {
 *                                                         literal: "SEV123",
 *                                                         reference: "incident.severity"
 *                                                     }
 *                                                 }],
 *                                             subject: "incident.severity"
 *                                         }]
 *                                 }]
 *                         },
 *                         navigate: {
 *                             reference: "catalog_attribute[\"01FCNDV6P870EA6S7TK1DSYD5H\"]"
 *                         },
 *                         operation_type: "navigate",
 *                         parse: {
 *                             returns: {
 *                                 array: true,
 *                                 type: "IncidentStatus"
 *                             },
 *                             source: "metadata.annotations[\"github.com/repo\"]"
 *                         }
 *                     }],
 *                 reference: "abc123",
 *                 root_reference: "incident.status"
 *             }],
 *         folder: "My folder 01",
 *         include_private_escalations: true,
 *         include_private_incidents: true,
 *         name: "My little workflow",
 *         once_for: ["incident.url"],
 *         runs_on_incident_modes: ["standard", "test", "retrospective"],
 *         runs_on_incidents: "newly_created",
 *         shortform: "page-the-ceo",
 *         state: "active",
 *         steps: [{
 *                 for_each: "abc123",
 *                 id: "abc123",
 *                 name: "pagerduty.escalate",
 *                 param_bindings: [{
 *                         array_value: [{
 *                                 literal: "SEV123",
 *                                 reference: "incident.severity"
 *                             }],
 *                         value: {
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }
 *                     }]
 *             }],
 *         trigger: "incident.updated"
 *     }
 */
export interface WorkflowsCreateWorkflowPayloadV2 {
    /** Annotations that track metadata about this resource */
    annotations?: Record<string, string>;
    /** Conditions that apply to the workflow trigger */
    condition_groups: FernApi.ConditionGroupPayloadV2[];
    /** Whether to continue executing the workflow if a step fails */
    continue_on_step_error: boolean;
    delay?: FernApi.WorkflowDelayV2;
    /** The expressions to use in the workflow */
    expressions: FernApi.ExpressionPayloadV2[];
    /** Folder to display the workflow in */
    folder?: string;
    /** Whether to include private escalations */
    include_private_escalations?: boolean;
    /** Whether to include private incidents */
    include_private_incidents: boolean;
    /** Name provided by the user when creating the workflow */
    name: string;
    /** This workflow will run 'once for' a list of references */
    once_for: string[];
    /** Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents. */
    runs_on_incident_modes: WorkflowsCreateWorkflowPayloadV2.RunsOnIncidentModes.Item[];
    /** Which incidents should the workflow be applied to? */
    runs_on_incidents: WorkflowsCreateWorkflowPayloadV2.RunsOnIncidents;
    /** The shortform used to trigger this workflow (only applicable for manual triggers) */
    shortform?: string;
    /** What state this workflow is in */
    state?: WorkflowsCreateWorkflowPayloadV2.State;
    /** Steps that are executed as part of the workflow */
    steps: FernApi.StepConfigPayloadV2[];
    /** Trigger to set on the workflow */
    trigger: string;
}

export namespace WorkflowsCreateWorkflowPayloadV2 {
    export type RunsOnIncidentModes = RunsOnIncidentModes.Item[];

    export namespace RunsOnIncidentModes {
        export const Item = {
            Standard: "standard",
            Test: "test",
            Retrospective: "retrospective",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    /** Which incidents should the workflow be applied to? */
    export const RunsOnIncidents = {
        NewlyCreated: "newly_created",
        NewlyCreatedAndActive: "newly_created_and_active",
    } as const;
    export type RunsOnIncidents = (typeof RunsOnIncidents)[keyof typeof RunsOnIncidents];
    /** What state this workflow is in */
    export const State = {
        Active: "active",
        Disabled: "disabled",
        Draft: "draft",
        Error: "error",
    } as const;
    export type State = (typeof State)[keyof typeof State];
}
