// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         alert_source_config_id: "01GW2G3V0S59R238FAHPDS1R66",
 *         token: "some-random-string",
 *         deduplication_key: "4293868629",
 *         description: "We've detected a number of timeouts on hello.world.com, the service may be down. To fix...",
 *         metadata: {
 *             "service": "hello.world.com",
 *             "team": [
 *                 "my-team"
 *             ]
 *         },
 *         source_url: "https://www.my-alerting-platform.com/alerts/my-alert-123",
 *         status: "firing",
 *         title: "*errors.withMessage: PG::Error failed to connect"
 *     }
 */
export interface AlertEventsCreateHttpPayloadV2 {
    /** Which alert source config produced this alert */
    alert_source_config_id: string;
    /** Token used to authenticate the request, generated when configuring the alert source. Will be consumed via a URL query string parameter */
    token?: string;
    /**
     * A deduplication key which uniquely references this alert from your alert source. For newly created HTTP sources, this field is required.
     * If you send an event with the same deduplication_key multiple times, only one alert will be created in incident.io for this alert source config.
     * You can filter on this field to find the alert created by an event you've sent us.
     */
    deduplication_key?: string;
    /** Description that optionally adds more detail to title. Supports markdown. */
    description?: string;
    /** Any additional metadata that you've configured your alert source to parse */
    metadata?: Record<string, unknown>;
    /** If applicable, a link to the alert in the upstream system */
    source_url?: string;
    /** Current status of this alert */
    status: AlertEventsCreateHttpPayloadV2.Status;
    /** The title of the alert, parsed from the alert payload according to the alert source configuration */
    title: string;
}

export namespace AlertEventsCreateHttpPayloadV2 {
    /** Current status of this alert */
    export const Status = {
        Firing: "firing",
        Resolved: "resolved",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
