// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *         attributes: [{
 *                 array: false,
 *                 backlink_attribute: "abc123",
 *                 id: "01GW2G3V0S59R238FAHPDS1R66",
 *                 mode: "",
 *                 name: "tier",
 *                 path: [{
 *                         attribute_id: "abc123"
 *                     }],
 *                 type: "Custom[\"Service\"]"
 *             }],
 *         version: 1
 *     }
 */
export interface CatalogUpdateTypeSchemaPayloadV3 {
    /** ID of this catalog type */
    id: string;
    attributes: FernApi.CatalogTypeAttributePayloadV3[];
    version: number;
}
