// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *         aliases: ["lawrence@incident.io", "lawrence"],
 *         attribute_values: {
 *             "abc123": {
 *                 array_value: [{
 *                         literal: "SEV123"
 *                     }],
 *                 value: {
 *                     literal: "SEV123"
 *                 }
 *             }
 *         },
 *         external_id: "761722cd-d1d7-477b-ac7e-90f9e079dc33",
 *         name: "Primary On-call",
 *         rank: 3,
 *         update_attributes: ["abc123"]
 *     }
 */
export interface CatalogUpdateEntryPayloadV3 {
    /** ID of this catalog entry */
    id: string;
    /** Optional aliases that can be used to reference this entry */
    aliases?: string[];
    /** Values of this entry */
    attribute_values: Record<string, IncidentIO.CatalogEngineParamBindingPayloadV3>;
    /** An optional alternative ID for this entry, which is ensured to be unique for the type */
    external_id?: string;
    /** Name is the human readable name of this entry */
    name: string;
    /** When catalog type is ranked, this is used to help order things */
    rank?: number;
    /**
     * If provided, only update these attribute_values keys. If not provided, update all attribute values.
     * If you specify an attribute key that's not in your payload, the associated attribute value will be cleared.
     */
    update_attributes?: string[];
}
