// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         catalog_type_id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *         page_size: 25,
 *         after: "01FDAG4SAP5TYPT98WGR2N7W91",
 *         identifier: "abc123"
 *     }
 */
export interface CatalogV3ListEntriesRequest {
    /** ID of this catalog type */
    catalog_type_id: string;
    /** The integer number of records to return */
    page_size: number;
    /** An record's ID. This endpoint will return a list of records after this ID in relation to the API response order. */
    after?: string;
    /**
     * If specified, only entries with this identifier will be returned. This will search by ID, external ID, and aliases.
     *
     * If 'use name as identifier' is enabled for the catalog type, this will also match on name.
     */
    identifier?: string;
}
