// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../../../../index.js";

/**
 * @example
 *     {
 *         aliases: ["lawrence@incident.io", "lawrence"],
 *         attribute_values: {
 *             "abc123": {
 *                 array_value: [{
 *                         literal: "SEV123"
 *                     }],
 *                 value: {
 *                     literal: "SEV123"
 *                 }
 *             }
 *         },
 *         catalog_type_id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *         external_id: "761722cd-d1d7-477b-ac7e-90f9e079dc33",
 *         name: "Primary On-call",
 *         rank: 3
 *     }
 */
export interface CatalogCreateEntryPayloadV3 {
    /** Optional aliases that can be used to reference this entry */
    aliases?: string[];
    /** Values of this entry */
    attribute_values: Record<string, IncidentIO.CatalogEngineParamBindingPayloadV3>;
    /** ID of this catalog type */
    catalog_type_id: string;
    /** An optional alternative ID for this entry, which is ensured to be unique for the type */
    external_id?: string;
    /** Name is the human readable name of this entry */
    name: string;
    /** When catalog type is ranked, this is used to help order things */
    rank?: number;
}
