// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "01FCNDV6P870EA6S7TK1DSYDG0"
 *     }
 */
export interface IncidentRolesV2DeleteRequest {
    /** Unique identifier for the role */
    id: string;
}
