// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         description: "The person currently coordinating the incident",
 *         instructions: "Take point on the incident; Make sure people are clear on responsibilities",
 *         name: "Incident Lead",
 *         shortform: "lead"
 *     }
 */
export interface IncidentRolesCreatePayloadV2 {
    /** Describes the purpose of the role */
    description: string;
    /** Provided to whoever is nominated for the role. Note that this will be empty for the 'reporter' role. */
    instructions: string;
    /** Human readable name of the incident role */
    name: string;
    /** Short human readable name for Slack. Note that this will be empty for the 'reporter' role. */
    shortform: string;
}
