// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../../../../index.js";

/**
 * @example
 *     {
 *         allowlist: [{
 *                 label: "London HQ",
 *                 value: "192.0.2.0"
 *             }],
 *         enabled: true,
 *         version: 1
 *     }
 */
export interface IpAllowlistsUpdateIpAllowlistPayloadV1 {
    /** A list of IP addresses or CIDR prefixes to allow */
    allowlist: IncidentIO.IpAllowlistItemV1[];
    /** Whether this IP allowlist is enabled or not */
    enabled: boolean;
    /** The version of this IP allowlist */
    version: number;
}
