// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *         sort_key: 10,
 *         value: "Product"
 *     }
 */
export interface CustomFieldOptionsUpdatePayloadV1 {
    /** Unique identifier for the custom field option */
    id: string;
    /** Sort key used to order the custom field options correctly */
    sort_key: number;
    /** Human readable name for the custom field option */
    value: string;
}
