// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *         sort_key: 10,
 *         value: "Product"
 *     }
 */
export interface CustomFieldOptionsCreatePayloadV1 {
    /** ID of the custom field this option belongs to */
    custom_field_id: string;
    /** Sort key used to order the custom field options correctly */
    sort_key?: number;
    /** Human readable name for the custom field option */
    value: string;
}
