// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "01FCNDV6P870EA6S7TK1DSYD5H",
 *         description: "Impact has been **fully mitigated**, and we're ready to learn from this incident.",
 *         name: "Closed"
 *     }
 */
export interface IncidentStatusesUpdatePayloadV1 {
    /** Unique ID of this incident status */
    id: string;
    /** Rich text description of the incident status */
    description: string;
    /** Unique name of this status */
    name: string;
}
