// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "01FCNDV6P870EA6S7TK1DSYD5H"
 *     }
 */
export interface IncidentStatusesV1ShowRequest {
    /** Unique ID of this incident status */
    id: string;
}
