// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../../../../index.js";

/**
 * @example
 *     {
 *         alert_sources: [{
 *                 alert_source_id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *                 condition_groups: [{
 *                         conditions: [{
 *                                 operation: "one_of",
 *                                 param_bindings: [{
 *                                         array_value: [{
 *                                                 literal: "SEV123",
 *                                                 reference: "incident.severity"
 *                                             }],
 *                                         value: {
 *                                             literal: "SEV123",
 *                                             reference: "incident.severity"
 *                                         }
 *                                     }],
 *                                 subject: "incident.severity"
 *                             }]
 *                     }]
 *             }],
 *         channel_config: [{
 *                 condition_groups: [{
 *                         conditions: [{
 *                                 operation: "one_of",
 *                                 param_bindings: [{
 *                                         array_value: [{
 *                                                 literal: "SEV123",
 *                                                 reference: "incident.severity"
 *                                             }],
 *                                         value: {
 *                                             literal: "SEV123",
 *                                             reference: "incident.severity"
 *                                         }
 *                                     }],
 *                                 subject: "incident.severity"
 *                             }]
 *                     }],
 *                 ms_teams_targets: {
 *                     binding: {
 *                         array_value: [{
 *                                 literal: "SEV123",
 *                                 reference: "incident.severity"
 *                             }],
 *                         value: {
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }
 *                     },
 *                     channel_visibility: "abc123"
 *                 },
 *                 slack_targets: {
 *                     binding: {
 *                         array_value: [{
 *                                 literal: "SEV123",
 *                                 reference: "incident.severity"
 *                             }],
 *                         value: {
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }
 *                     },
 *                     channel_visibility: "abc123"
 *                 }
 *             }],
 *         condition_groups: [{
 *                 conditions: [{
 *                         operation: "one_of",
 *                         param_bindings: [{
 *                                 array_value: [{
 *                                         literal: "SEV123",
 *                                         reference: "incident.severity"
 *                                     }],
 *                                 value: {
 *                                     literal: "SEV123",
 *                                     reference: "incident.severity"
 *                                 }
 *                             }],
 *                         subject: "incident.severity"
 *                     }]
 *             }],
 *         created_at: "2021-08-17T13:28:57Z",
 *         enabled: false,
 *         escalation_config: {
 *             auto_cancel_escalations: false,
 *             escalation_targets: [{
 *                     escalation_paths: {
 *                         array_value: [{
 *                                 literal: "SEV123",
 *                                 reference: "incident.severity"
 *                             }],
 *                         value: {
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }
 *                     },
 *                     users: {
 *                         array_value: [{
 *                                 literal: "SEV123",
 *                                 reference: "incident.severity"
 *                             }],
 *                         value: {
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }
 *                     }
 *                 }]
 *         },
 *         expressions: [{
 *                 else_branch: {
 *                     result: {
 *                         array_value: [{
 *                                 literal: "SEV123",
 *                                 reference: "incident.severity"
 *                             }],
 *                         value: {
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }
 *                     }
 *                 },
 *                 label: "Team Slack channel",
 *                 operations: [{
 *                         branches: {
 *                             branches: [{
 *                                     condition_groups: [{
 *                                             conditions: [{
 *                                                     operation: "one_of",
 *                                                     param_bindings: [{
 *                                                             array_value: [{
 *                                                                     literal: "SEV123",
 *                                                                     reference: "incident.severity"
 *                                                                 }],
 *                                                             value: {
 *                                                                 literal: "SEV123",
 *                                                                 reference: "incident.severity"
 *                                                             }
 *                                                         }],
 *                                                     subject: "incident.severity"
 *                                                 }]
 *                                         }],
 *                                     result: {
 *                                         array_value: [{
 *                                                 literal: "SEV123",
 *                                                 reference: "incident.severity"
 *                                             }],
 *                                         value: {
 *                                             literal: "SEV123",
 *                                             reference: "incident.severity"
 *                                         }
 *                                     }
 *                                 }],
 *                             returns: {
 *                                 array: true,
 *                                 type: "IncidentStatus"
 *                             }
 *                         },
 *                         concatenate: {
 *                             reference: "catalog_attribute[\"01FCNDV6P870EA6S7TK1DSYD5H\"]"
 *                         },
 *                         filter: {
 *                             condition_groups: [{
 *                                     conditions: [{
 *                                             operation: "one_of",
 *                                             param_bindings: [{
 *                                                     array_value: [{
 *                                                             literal: "SEV123",
 *                                                             reference: "incident.severity"
 *                                                         }],
 *                                                     value: {
 *                                                         literal: "SEV123",
 *                                                         reference: "incident.severity"
 *                                                     }
 *                                                 }],
 *                                             subject: "incident.severity"
 *                                         }]
 *                                 }]
 *                         },
 *                         navigate: {
 *                             reference: "catalog_attribute[\"01FCNDV6P870EA6S7TK1DSYD5H\"]"
 *                         },
 *                         operation_type: "navigate",
 *                         parse: {
 *                             returns: {
 *                                 array: true,
 *                                 type: "IncidentStatus"
 *                             },
 *                             source: "metadata.annotations[\"github.com/repo\"]"
 *                         }
 *                     }],
 *                 reference: "abc123",
 *                 root_reference: "incident.status"
 *             }],
 *         incident_config: {
 *             auto_decline_enabled: false,
 *             auto_relate_grouped_alerts: false,
 *             condition_groups: [{
 *                     conditions: [{
 *                             operation: "one_of",
 *                             param_bindings: [{
 *                                     array_value: [{
 *                                             literal: "SEV123",
 *                                             reference: "incident.severity"
 *                                         }],
 *                                     value: {
 *                                         literal: "SEV123",
 *                                         reference: "incident.severity"
 *                                     }
 *                                 }],
 *                             subject: "incident.severity"
 *                         }]
 *                 }],
 *             defer_time_seconds: 1,
 *             enabled: false,
 *             grouping_keys: [{
 *                     reference: "alert.title"
 *                 }],
 *             grouping_window_seconds: 1
 *         },
 *         incident_template: {
 *             custom_fields: [{
 *                     binding: {
 *                         array_value: [{
 *                                 literal: "SEV123",
 *                                 reference: "incident.severity"
 *                             }],
 *                         value: {
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }
 *                     },
 *                     custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *                     merge_strategy: "first-wins"
 *                 }],
 *             incident_mode: {
 *                 binding: {
 *                     array_value: [{
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }],
 *                     value: {
 *                         literal: "SEV123",
 *                         reference: "incident.severity"
 *                     }
 *                 }
 *             },
 *             incident_type: {
 *                 binding: {
 *                     array_value: [{
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }],
 *                     value: {
 *                         literal: "SEV123",
 *                         reference: "incident.severity"
 *                     }
 *                 }
 *             },
 *             name: {
 *                 autogenerated: false,
 *                 binding: {
 *                     array_value: [{
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }],
 *                     value: {
 *                         literal: "SEV123",
 *                         reference: "incident.severity"
 *                     }
 *                 }
 *             },
 *             severity: {
 *                 binding: {
 *                     array_value: [{
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }],
 *                     value: {
 *                         literal: "SEV123",
 *                         reference: "incident.severity"
 *                     }
 *                 },
 *                 merge_strategy: "first-wins"
 *             },
 *             start_in_triage: {
 *                 binding: {
 *                     array_value: [{
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }],
 *                     value: {
 *                         literal: "SEV123",
 *                         reference: "incident.severity"
 *                     }
 *                 }
 *             },
 *             summary: {
 *                 autogenerated: false,
 *                 binding: {
 *                     array_value: [{
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }],
 *                     value: {
 *                         literal: "SEV123",
 *                         reference: "incident.severity"
 *                     }
 *                 }
 *             },
 *             workspace: {
 *                 binding: {
 *                     array_value: [{
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }],
 *                     value: {
 *                         literal: "SEV123",
 *                         reference: "incident.severity"
 *                     }
 *                 }
 *             }
 *         },
 *         is_private: false,
 *         name: "Production incidents",
 *         owning_team_ids: ["01G0J1EXE7AXZ2C93K61WBPYEH"],
 *         updated_at: "2021-08-17T13:28:57Z",
 *         version: 1
 *     }
 */
export interface AlertRoutesCreatePayloadV2 {
    /** Which alert sources should this alert route match? */
    alert_sources: FernApi.AlertRouteAlertSourcePayloadV2[];
    /** The channel configuration for this alert route */
    channel_config: FernApi.AlertRouteChannelConfigPayloadV2[];
    /** What condition groups must be true for this alert route to fire? */
    condition_groups: FernApi.ConditionGroupPayloadV2[];
    /** The time of creation of this alert route */
    created_at?: string;
    /** Whether this alert route is enabled or not */
    enabled: boolean;
    escalation_config: FernApi.AlertRouteEscalationConfigPayloadV2;
    /** The expressions used in this template */
    expressions: FernApi.ExpressionPayloadV2[];
    incident_config: FernApi.AlertRouteIncidentConfigPayloadV2;
    incident_template: FernApi.AlertRouteIncidentTemplatePayloadV2;
    /** Whether this alert route is private. Private alert routes will only create private incidents from alerts. */
    is_private: boolean;
    /** The name of this alert route config, for the user's reference */
    name: string;
    /** IDs of teams that own this alert route */
    owning_team_ids?: string[];
    /** The time of last update of this alert route */
    updated_at?: string;
    /** The version of this alert route config */
    version: number;
}
