// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         page_size: 25,
 *         after: "01FCNDV6P870EA6S7TK1DSYDG0"
 *     }
 */
export interface AlertRoutesV2ListRequest {
    /** Number of alert routes to return per page */
    page_size: number;
    /** The ID of the last alert route on the previous page */
    after?: string;
}
