// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../../../../index.js";

/**
 * @example
 *     {
 *         incident_id: "01FCNDV6P870EA6S7TK1DSYDG0"
 *     }
 */
export interface FollowUpsV2ListRequest {
    /** Find follow-ups related to this incident */
    incident_id?: string;
    /** Filter to follow-ups from incidents of the given mode. If not set, only follow-ups from `standard` and `retrospective` incidents are returned */
    incident_mode?: FernApi.FollowUpsV2ListRequestIncidentMode;
}
