// This file was auto-generated by Fern from our API Definition.

/** Filter to actions from incidents of the given mode. If not set, only actions from `standard` and `retrospective` incidents are returned */
export const ActionsV2ListRequestIncidentMode = {
    Standard: "standard",
    Retrospective: "retrospective",
    Test: "test",
    Tutorial: "tutorial",
    Stream: "stream",
} as const;
export type ActionsV2ListRequestIncidentMode =
    (typeof ActionsV2ListRequestIncidentMode)[keyof typeof ActionsV2ListRequestIncidentMode];
