// This file was auto-generated by Fern from our API Definition.

export interface AfterPaginationMetaResultV2 {
    /** The time, if it exists, of the last entry's end time */
    after: string;
    /** The URL to fetch the next page of entries */
    after_url: string;
}
