// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface AlertRouteIncidentTemplateV2 {
    /** Custom fields configuration */
    custom_fields?: IncidentIO.AlertRouteCustomFieldBindingV2[];
    incident_mode?: IncidentIO.AlertRouteTemplateBindingV2;
    incident_type?: IncidentIO.AlertRouteTemplateBindingV2;
    name: IncidentIO.AlertRouteAutoGeneratedTemplateBindingV2;
    severity?: IncidentIO.AlertRouteSeverityBindingV2;
    start_in_triage?: IncidentIO.AlertRouteTemplateBindingV2;
    summary?: IncidentIO.AlertRouteAutoGeneratedTemplateBindingV2;
    workspace?: IncidentIO.AlertRouteTemplateBindingV2;
}
