// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface AlertRouteIncidentConfigPayloadV2 {
    /** Should triage incidents be declined when alerts are resolved? */
    auto_decline_enabled: boolean;
    /** Should grouped alerts automatically be related to active incidents without confirmation? */
    auto_relate_grouped_alerts?: boolean;
    /** What condition groups must be true for this alert route to create an incident? */
    condition_groups: IncidentIO.ConditionGroupPayloadV2[];
    /** How long should the escalation defer time be? */
    defer_time_seconds: number;
    /** Whether incident creation is enabled for this alert route */
    enabled: boolean;
    /** Which attributes should this alert route use to group alerts? */
    grouping_keys: IncidentIO.GroupingKeyV2[];
    /** How large should the grouping window be? */
    grouping_window_seconds: number;
}
