// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface AlertSourcesUpdateResultV2 {
    alert_source: FernApi.AlertSourceV2;
}
