// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface AlertRouteAutoGeneratedTemplateBindingPayloadV2 {
    /** Whether this attribute is autogenerated using AI or not */
    autogenerated?: boolean;
    binding?: IncidentIO.EngineParamBindingPayloadV2;
}
