// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface AlertRouteChannelConfigPayloadV2 {
    /** The conditions that must be met for this channel config to be used */
    condition_groups: IncidentIO.ConditionGroupPayloadV2[];
    ms_teams_targets?: IncidentIO.AlertRouteChannelTargetPayloadV2;
    slack_targets?: IncidentIO.AlertRouteChannelTargetPayloadV2;
}
