// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface AlertRouteTemplateBindingV2 {
    binding?: IncidentIO.EngineParamBindingV2;
}
