// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface AlertsListResultV2 {
    alerts: IncidentIO.AlertV2[];
    pagination_meta: IncidentIO.PaginationMetaResultV2;
}
