// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface AlertAttributesListResultV2 {
    alert_attributes: FernApi.AlertAttributeV2[];
}
