// This file was auto-generated by Fern from our API Definition.

export interface AlertSourceHttpCustomOptionsV2 {
    /** JSON path to extract the deduplication key from the payload */
    deduplication_key_path: string;
    /** JavaScript expression that returns an object with all alert fields */
    transform_expression: string;
}
