// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface AlertRouteEscalationTargetPayloadV2 {
    escalation_paths?: IncidentIO.EngineParamBindingPayloadV2;
    users?: IncidentIO.EngineParamBindingPayloadV2;
}
