// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface AlertV2 {
    /** The ID of the alert source this alert fired on */
    alert_source_id: string;
    /** Attribute values parsed from the alerts payload */
    attributes: FernApi.AlertAttributeEntryV2[];
    /** When this entry was created */
    created_at: string;
    /**
     * A deduplication key which uniquely references this alert from your alert source. For newly created HTTP sources, this field is required.
     * If you send an event with the same deduplication_key multiple times, only one alert will be created in incident.io for this alert source config.
     * You can filter on this field to find the alert created by an event you've sent us.
     */
    deduplication_key: string;
    /** The description of the alert */
    description?: string;
    /** The ID of this alert */
    id: string;
    /** When this alert was resolved */
    resolved_at?: string;
    /** If applicable, a link to the alert in the upstream system */
    source_url?: string;
    /** Statuses of an alert */
    status: AlertV2.Status;
    /** The title of the alert, parsed from the alert payload according to the alert source configuration */
    title: string;
    /** When this alert was last updated */
    updated_at: string;
}

export namespace AlertV2 {
    /** Statuses of an alert */
    export const Status = {
        Firing: "firing",
        Resolved: "resolved",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
