// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface AlertTemplateAttributeV2 {
    /** ID of the alert attribute to set with this binding */
    alert_attribute_id: string;
    binding: IncidentIO.EngineParamBindingV2;
}
