// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface AlertTemplateV2 {
    /** Attributes to set on alerts coming from this source, with a binding describing how to set them. */
    attributes: FernApi.AlertTemplateAttributeV2[];
    description: FernApi.EngineParamBindingValueV2;
    /** Expressions available for use in bindings within this template */
    expressions: FernApi.ExpressionV2[];
    /** Whether or not alerts produced by this source should be private */
    is_private: boolean;
    title: FernApi.EngineParamBindingValueV2;
    visible_to_teams?: FernApi.EngineParamBindingV2;
}
