// This file was auto-generated by Fern from our API Definition.

export interface AlertAttributeCatalogEntryV2 {
    /** ID of this catalog type */
    catalog_type_id: string;
    /** ID of this catalog entry */
    id: string;
    /** Name is the human readable name of this entry */
    name: string;
}
