// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface AlertRouteEscalationTargetPayloadV2 {
    escalation_paths?: FernApi.EngineParamBindingPayloadV2;
    users?: FernApi.EngineParamBindingPayloadV2;
}
