// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface AlertRouteChannelTargetV2 {
    binding: IncidentIO.EngineParamBindingV2;
    /** The visibility of the channel */
    channel_visibility: string;
}
