// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface AlertRouteChannelConfigV2 {
    /** The conditions that must be met for this channel config to be used */
    condition_groups: FernApi.ConditionGroupV2[];
    ms_teams_targets?: FernApi.AlertRouteChannelTargetV2;
    slack_targets?: FernApi.AlertRouteChannelTargetV2;
}
