// This file was auto-generated by Fern from our API Definition.

export interface AlertSourceJiraOptionsV2 {
    /** Which projects in Jira should this alert source watch for new issues? IDs can either be IDs of the projects in Jira, or ID of catalog entries in the 'Jira Project' catalog type. */
    project_ids: string[];
}
