// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface AlertRouteV2 {
    /** Which alert sources should this alert route match? */
    alert_sources: FernApi.AlertRouteAlertSourceV2[];
    /** The channel configuration for this alert route */
    channel_config: FernApi.AlertRouteChannelConfigV2[];
    /** What condition groups must be true for this alert route to fire? */
    condition_groups: FernApi.ConditionGroupV2[];
    /** The time of creation of this alert route */
    created_at?: string;
    /** Whether this alert route is enabled or not */
    enabled: boolean;
    escalation_config: FernApi.AlertRouteEscalationConfigV2;
    /** The expressions used in this template */
    expressions: FernApi.ExpressionV2[];
    /** Unique identifier for this alert route config */
    id: string;
    incident_config: FernApi.AlertRouteIncidentConfigV2;
    incident_template: FernApi.AlertRouteIncidentTemplateV2;
    /** Whether this alert route is private. Private alert routes will only create private incidents from alerts. */
    is_private: boolean;
    /** The name of this alert route config, for the user's reference */
    name: string;
    /** IDs of teams that own this alert route */
    owning_team_ids?: string[];
    /** The time of last update of this alert route */
    updated_at?: string;
    /** The version of this alert route config */
    version: number;
}
