// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface AlertTemplatePayloadV2 {
    /** Attributes to set on alerts coming from this source, with a binding describing how to set them. */
    attributes: IncidentIO.AlertTemplateAttributePayloadV2[];
    description: IncidentIO.EngineParamBindingValuePayloadV2;
    /** Expressions available for use in bindings within this template */
    expressions: IncidentIO.ExpressionPayloadV2[];
    /** Whether or not alerts produced by this source should be private */
    is_private?: boolean;
    title: IncidentIO.EngineParamBindingValuePayloadV2;
    visible_to_teams?: IncidentIO.EngineParamBindingPayloadV2;
}
