// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface AlertTemplatePayloadV2 {
    /** Attributes to set on alerts coming from this source, with a binding describing how to set them. */
    attributes: FernApi.AlertTemplateAttributePayloadV2[];
    description: FernApi.EngineParamBindingValuePayloadV2;
    /** Expressions available for use in bindings within this template */
    expressions: FernApi.ExpressionPayloadV2[];
    /** Whether or not alerts produced by this source should be private */
    is_private?: boolean;
    title: FernApi.EngineParamBindingValuePayloadV2;
    visible_to_teams?: FernApi.EngineParamBindingPayloadV2;
}
