// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface AlertsListIncidentAlertsResultV2 {
    incident_alerts: FernApi.IncidentAlertV2[];
    pagination_meta: FernApi.PaginationMetaResultV2;
}
