// This file was auto-generated by Fern from our API Definition.

export interface ApiKeyV2 {
    /** Unique identifier for this API key */
    id: string;
    /** The name of the API key, for the user's reference */
    name: string;
}
