// This file was auto-generated by Fern from our API Definition.

export interface AuditLogUserRoleMembershipChangedMetadataV2 {
    /** The base role slug of the user after their role memberships changed */
    after_base_role_slug: string;
    /** The custom role slugs of the user after their role memberships changed, separated by commas */
    after_custom_role_slugs: string;
    /** The base role slug of the user before their role memberships changed */
    before_base_role_slug: string;
    /** The custom role slugs of the user before their role memberships changed, separated by commas */
    before_custom_role_slugs: string;
}
