// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface AuditLogsHolidayUserFeedCreatedV1 {
    /** The type of log entry that this is */
    action: string;
    actor: FernApi.AuditLogActorV2;
    context: FernApi.AuditLogEntryContextV2;
    /** When the entry occurred */
    occurred_at: string;
    /** The custom field that was created */
    targets: FernApi.AuditLogTargetV2[];
    /** Which version the event is */
    version: number;
}
