// This file was auto-generated by Fern from our API Definition.

export interface AuditLogEntryContextV2 {
    /** The location of the actor that performed this action */
    location: string;
    /** The user agent of the actor that performed this action */
    user_agent?: string;
}
