// This file was auto-generated by Fern from our API Definition.

export interface AuditLogCatalogAttributeUpdatedMetadataV2V2 {
    /** The user IDs that were in the attribute before the change, comma separated */
    after_values: string;
    /** The user IDs that were in the attribute before the change, comma separated */
    before_values: string;
}
