// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface AuditLogsScheduleCreatedV1 {
    /** The type of log entry that this is */
    action: string;
    actor: IncidentIO.AuditLogActorV2;
    context: IncidentIO.AuditLogEntryContextV2;
    /** When the entry occurred */
    occurred_at: string;
    /** The custom field that was created */
    targets: IncidentIO.AuditLogTargetV2[];
    /** Which version the event is */
    version: number;
}
