// This file was auto-generated by Fern from our API Definition.

export interface AuditLogPrivateIncidentAccessAttemptedMetadataV2 {
    /** Whether or not the user was able to access the private incident */
    outcome?: AuditLogPrivateIncidentAccessAttemptedMetadataV2.Outcome;
}

export namespace AuditLogPrivateIncidentAccessAttemptedMetadataV2 {
    /** Whether or not the user was able to access the private incident */
    export const Outcome = {
        Granted: "granted",
        Denied: "denied",
    } as const;
    export type Outcome = (typeof Outcome)[keyof typeof Outcome];
}
