// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface CatalogEngineParamBindingPayloadV3 {
    /** If set, this is the array value of the step parameter */
    array_value?: IncidentIO.CatalogEngineParamBindingValuePayloadV3[];
    value?: IncidentIO.CatalogEngineParamBindingValuePayloadV3;
}
