// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface CatalogEntryEngineParamBindingV2 {
    /** If array_value is set, this helps render the values */
    array_value?: FernApi.CatalogEntryEngineParamBindingValueV2[];
    value?: FernApi.CatalogEntryEngineParamBindingValueV2;
}
