// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface CatalogListTypesResultV2 {
    catalog_types: FernApi.CatalogTypeV2[];
}
