// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface CatalogTypeSchemaV2 {
    /** Attributes of this catalog type */
    attributes: IncidentIO.CatalogTypeAttributeV2[];
    /** The version number of this schema */
    version: number;
}
