// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface CatalogTypeSchemaV3 {
    /** Attributes of this catalog type */
    attributes: IncidentIO.CatalogTypeAttributeV3[];
    /** The version number of this schema */
    version: number;
}
