// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface CatalogCreateTypeResultV2 {
    catalog_type: IncidentIO.CatalogTypeV2;
}
