// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface CatalogTypeAttributeV3 {
    /** Whether this attribute is an array */
    array: boolean;
    /** The attribute to use (if this is a backlink) */
    backlink_attribute?: string;
    /** The ID of this attribute */
    id: string;
    /** Controls how this attribute is modified */
    mode: CatalogTypeAttributeV3.Mode;
    /** Unique name of this attribute */
    name: string;
    /** The path to use (if this is a path attribute) */
    path?: IncidentIO.CatalogTypeAttributePathItemV3[];
    /** Catalog type name for this attribute */
    type: string;
}

export namespace CatalogTypeAttributeV3 {
    /** Controls how this attribute is modified */
    export const Mode = {
        Empty: "",
        Api: "api",
        Dashboard: "dashboard",
        External: "external",
        Internal: "internal",
        Dynamic: "dynamic",
        Backlink: "backlink",
        Path: "path",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
}
