// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface CatalogEntryV2 {
    /** Optional aliases that can be used to reference this entry */
    aliases: string[];
    /** When this entry was archived */
    archived_at?: string;
    /** Values of this entry */
    attribute_values: Record<string, FernApi.CatalogEntryEngineParamBindingV2>;
    /** ID of this catalog type */
    catalog_type_id: string;
    /** When this entry was created */
    created_at: string;
    /** An optional alternative ID for this entry, which is ensured to be unique for the type */
    external_id?: string;
    /** ID of this catalog entry */
    id: string;
    /** Name is the human readable name of this entry */
    name: string;
    /** When catalog type is ranked, this is used to help order things */
    rank: number;
    /** When this entry was last updated */
    updated_at: string;
}
