// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface CatalogUpdateEntryResultV3 {
    catalog_entry: IncidentIO.CatalogEntryV3;
    catalog_type: IncidentIO.CatalogTypeV3;
}
