// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface CatalogListEntriesResultV2 {
    catalog_entries: FernApi.CatalogEntryV2[];
    catalog_type: FernApi.CatalogTypeV2;
    pagination_meta: FernApi.PaginationMetaResultV2;
}
