// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface CatalogUpdateTypeResultV3 {
    catalog_type: FernApi.CatalogTypeV3;
}
