// This file was auto-generated by Fern from our API Definition.

export interface CatalogEntryReferenceV2 {
    /** When this entry was archived */
    archived_at?: string;
    /** ID of this catalog entry */
    catalog_entry_id: string;
    /** The name of this entry */
    catalog_entry_name: string;
    /** ID of this catalog type */
    catalog_type_id: string;
}
