// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface CatalogTypeV2 {
    /** Annotations that can track metadata about this type */
    annotations: Record<string, string>;
    /** What categories is this type considered part of */
    categories: CatalogTypeV2.Categories.Item[];
    /** Sets the display color of this type in the dashboard */
    color: CatalogTypeV2.Color;
    /** When this type was created */
    created_at: string;
    /** Human readble description of this type */
    description: string;
    /** If this is a dynamic catalog type, this will be the unique parameter for identitfying this resource externally. */
    dynamic_resource_parameter?: string;
    /** If populated, gives an estimated count of entries for this type */
    estimated_count?: number;
    /** Sets the display icon of this type in the dashboard */
    icon: CatalogTypeV2.Icon;
    /** ID of this catalog type */
    id: string;
    /** Catalog types that are synced with external resources can't be edited */
    is_editable: boolean;
    /** When this type was last synced (if it's ever been sync'd) */
    last_synced_at?: string;
    /** Name is the human readable name of this type */
    name: string;
    /** If this type should be ranked */
    ranked: boolean;
    /** The registry resource this type is synced from, if any */
    registry_type?: string;
    /** If populated, the integrations required for this type */
    required_integrations?: string[];
    schema: IncidentIO.CatalogTypeSchemaV2;
    /** This type has been deprecated, and will always be empty. */
    semantic_type: string;
    /** The url of the external repository where this type is managed */
    source_repo_url?: string;
    /** The type name of this catalog type, to be used when defining attributes. This is immutable once a CatalogType has been created. For non-externally sync types, it must follow the pattern Custom["SomeName"] */
    type_name: string;
    /** When this type was last updated */
    updated_at: string;
}

export namespace CatalogTypeV2 {
    export type Categories = Categories.Item[];

    export namespace Categories {
        export const Item = {
            Customer: "customer",
            IssueTracker: "issue-tracker",
            ProductFeature: "product-feature",
            Service: "service",
            OnCall: "on-call",
            Team: "team",
            User: "user",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    /** Sets the display color of this type in the dashboard */
    export const Color = {
        Yellow: "yellow",
        Green: "green",
        Blue: "blue",
        Violet: "violet",
        Pink: "pink",
        Cyan: "cyan",
        Orange: "orange",
    } as const;
    export type Color = (typeof Color)[keyof typeof Color];
    /** Sets the display icon of this type in the dashboard */
    export const Icon = {
        Alert: "alert",
        Bolt: "bolt",
        Box: "box",
        Briefcase: "briefcase",
        Browser: "browser",
        Bulb: "bulb",
        Calendar: "calendar",
        Clock: "clock",
        Cog: "cog",
        Components: "components",
        Database: "database",
        Doc: "doc",
        Email: "email",
        EscalationPath: "escalation-path",
        Files: "files",
        Flag: "flag",
        Folder: "folder",
        Globe: "globe",
        Money: "money",
        Server: "server",
        Severity: "severity",
        StatusPage: "status-page",
        Store: "store",
        Star: "star",
        Tag: "tag",
        User: "user",
        Users: "users",
    } as const;
    export type Icon = (typeof Icon)[keyof typeof Icon];
}
