// This file was auto-generated by Fern from our API Definition.

export interface ConditionOperationV2 {
    /** Human readable label to be displayed for user to select */
    label: string;
    /** Unique identifier for this option */
    value: string;
}
