// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface CustomFieldsListResultV2 {
    custom_fields: IncidentIO.CustomFieldV2[];
}
