// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface CustomFieldEntryPayloadV1 {
    /** ID of the custom field this entry is linked against */
    custom_field_id: string;
    /** List of values to associate with this entry. Use an empty array to unset the value of the custom field. */
    values: FernApi.CustomFieldValuePayloadV1[];
}
