// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface CustomFieldEntryV1 {
    custom_field: IncidentIO.CustomFieldTypeInfoV1;
    /** List of custom field values set on this entry */
    values: IncidentIO.CustomFieldValueV1[];
}
