// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface CustomFieldOptionsListResultV1 {
    custom_field_options: IncidentIO.CustomFieldOptionV1[];
    pagination_meta: IncidentIO.PaginationMetaResultV1;
}
