// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface CustomFieldOptionsCreateResultV1 {
    custom_field_option: IncidentIO.CustomFieldOptionV1;
}
