// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface CustomFieldsCreateResultV2 {
    custom_field: FernApi.CustomFieldV2;
}
