// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface CustomFieldValueV2 {
    value_catalog_entry?: IncidentIO.EmbeddedCatalogEntryV2;
    /** If the custom field type is 'link', this will contain the value assigned. */
    value_link?: string;
    /** If the custom field type is 'numeric', this will contain the value assigned. */
    value_numeric?: string;
    value_option?: IncidentIO.CustomFieldOptionV2;
    /** If the custom field type is 'text', this will contain the value assigned. */
    value_text?: string;
}
