// This file was auto-generated by Fern from our API Definition.

export interface CustomFieldValuePayloadV1 {
    /** Unique identifier for the custom field value */
    id?: string;
    /** ID of the catalog entry. You can also use an ExternalID or an Alias of the catalog entry. */
    value_catalog_entry_id?: string;
    /** If the custom field type is 'link', this will contain the value assigned. */
    value_link?: string;
    /** If the custom field type is 'numeric', this will contain the value assigned. */
    value_numeric?: string;
    /** ID of the custom field option */
    value_option_id?: string;
    /** If the custom field type is 'text', this will contain the value assigned. */
    value_text?: string;
    /** Deprecated: please use incident timestamp values instead */
    value_timestamp?: string;
}
