// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface EscalationsUpdatePathResultV2 {
    escalation_path: IncidentIO.EscalationPathV2;
}
