// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface EscalationEventV2 {
    /** This field will be populated for notified_channels events. */
    channels?: FernApi.ChatChannelSlimV2[];
    /** The type of event that occured. */
    event: EscalationEventV2.Event;
    /** The unique ID for this escalation event */
    id: string;
    /** The time when this escalation event was processed */
    occurred_at: string;
    /** The urgency at which we tried to notify users. This field will be populated for notified_users events. */
    urgency?: EscalationEventV2.Urgency;
    /** This field will be populated for notified_users and acked events. */
    users?: FernApi.UserV2[];
}

export namespace EscalationEventV2 {
    /** The type of event that occured. */
    export const Event = {
        EnteredGracePeriod: "entered_grace_period",
        Triggered: "triggered",
        NotifiedUsers: "notified_users",
        NotifiedChannels: "notified_channels",
        Acked: "acked",
        Cancelled: "cancelled",
        Resolved: "resolved",
        Expired: "expired",
    } as const;
    export type Event = (typeof Event)[keyof typeof Event];
    /** The urgency at which we tried to notify users. This field will be populated for notified_users events. */
    export const Urgency = {
        High: "high",
        Low: "low",
    } as const;
    export type Urgency = (typeof Urgency)[keyof typeof Urgency];
}
