// This file was auto-generated by Fern from our API Definition.

export interface EscalationPathTargetV2 {
    /** Uniquely identifies an entity of this type */
    id: string;
    /** Only set for schedule targets, and either currently_on_call, all_users or all_users_for_rota and specifies which users to fetch from the schedule */
    schedule_mode?: EscalationPathTargetV2.ScheduleMode;
    /** Controls what type of entity this target identifies, such as EscalationPolicy or User */
    type: EscalationPathTargetV2.Type;
    /** The urgency of this escalation path target */
    urgency: EscalationPathTargetV2.Urgency;
}

export namespace EscalationPathTargetV2 {
    /** Only set for schedule targets, and either currently_on_call, all_users or all_users_for_rota and specifies which users to fetch from the schedule */
    export const ScheduleMode = {
        CurrentlyOnCall: "currently_on_call",
        AllUsersForRota: "all_users_for_rota",
        AllUsers: "all_users",
        Empty: "",
    } as const;
    export type ScheduleMode = (typeof ScheduleMode)[keyof typeof ScheduleMode];
    /** Controls what type of entity this target identifies, such as EscalationPolicy or User */
    export const Type = {
        Schedule: "schedule",
        User: "user",
        SlackChannel: "slack_channel",
        MsteamsChannel: "msteams_channel",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** The urgency of this escalation path target */
    export const Urgency = {
        High: "high",
        Low: "low",
    } as const;
    export type Urgency = (typeof Urgency)[keyof typeof Urgency];
}
