// This file was auto-generated by Fern from our API Definition.

export interface EscalationPathRoundRobinConfigV2 {
    /** Whether round robin is enabled for this level */
    enabled: boolean;
    /** How long should we wait before rotating to the next target in a round robin, if not set will stick with a single target per level. */
    rotate_after_seconds?: number;
}
