// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface EscalationPathNodeIfElsePayloadV2 {
    /** The condition that defines which branch to take */
    conditions?: IncidentIO.ConditionPayloadV2[];
    /** The nodes that form the levels if our condition is not met */
    else_path: IncidentIO.EscalationPathNodePayloadV2[];
    /** The nodes that form the levels if our condition is met */
    then_path: IncidentIO.EscalationPathNodePayloadV2[];
}
