// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface EscalationPathV2 {
    /** Users who are currently on-call for this escalation path */
    current_responders?: FernApi.UserV2[];
    /** Unique identifier for this escalation path. */
    id: string;
    /** The name of this escalation path, for the user's reference. */
    name: string;
    /** The nodes that form the levels and branches of this escalation path. */
    path: FernApi.EscalationPathNodeV2[];
    /** IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required. */
    team_ids: string[];
    /** The working hours for this escalation path. */
    working_hours?: FernApi.WeekdayIntervalConfigV2[];
}
