// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface EscalationPathNodeV2 {
    /**
     * An ID for this node, unique within the escalation path.
     *
     * This allows you to reference the node in other nodes, such as when configuring a 'repeat' node.
     */
    id: string;
    if_else?: FernApi.EscalationPathNodeIfElseV2;
    level?: FernApi.EscalationPathNodeLevelV2;
    notify_channel?: FernApi.EscalationPathNodeNotifyChannelV2;
    repeat?: FernApi.EscalationPathNodeRepeatV2;
    /**
     * The type of this node. Available types are:
     * * level: A set of targets (users or schedules) that should be paged, either all at once, or with a round-robin configuration.
     * * notify_channel: Send the escalation to a Slack channel, where it can be acked by anyone in the channel.
     * * if_else: Branch the escalation based on a set of conditions.
     * * repeat: Go back to a previous node and repeat the logic from there.
     */
    type: EscalationPathNodeV2.Type;
}

export namespace EscalationPathNodeV2 {
    /**
     * The type of this node. Available types are:
     * * level: A set of targets (users or schedules) that should be paged, either all at once, or with a round-robin configuration.
     * * notify_channel: Send the escalation to a Slack channel, where it can be acked by anyone in the channel.
     * * if_else: Branch the escalation based on a set of conditions.
     * * repeat: Go back to a previous node and repeat the logic from there.
     */
    export const Type = {
        IfElse: "if_else",
        Repeat: "repeat",
        Level: "level",
        NotifyChannel: "notify_channel",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
