// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface ExpressionOperationPayloadV2 {
    branches?: IncidentIO.ExpressionBranchesOptsPayloadV2;
    concatenate?: IncidentIO.ExpressionConcatenateOptsPayloadV2;
    filter?: IncidentIO.ExpressionFilterOptsPayloadV2;
    navigate?: IncidentIO.ExpressionNavigateOptsPayloadV2;
    /** The type of the operation */
    operation_type: ExpressionOperationPayloadV2.OperationType;
    parse?: IncidentIO.ExpressionParseOptsPayloadV2;
}

export namespace ExpressionOperationPayloadV2 {
    /** The type of the operation */
    export const OperationType = {
        Navigate: "navigate",
        Filter: "filter",
        Concatenate: "concatenate",
        Count: "count",
        Min: "min",
        Max: "max",
        Sum: "sum",
        Random: "random",
        First: "first",
        Parse: "parse",
        Branches: "branches",
    } as const;
    export type OperationType = (typeof OperationType)[keyof typeof OperationType];
}
