// This file was auto-generated by Fern from our API Definition.

export interface ExpressionNavigateOptsV2 {
    /** The reference within the scope to navigate to */
    reference: string;
    /** The name of the reference to navigate to */
    reference_label: string;
}
