// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface ExpressionV2 {
    else_branch?: FernApi.ExpressionElseBranchV2;
    /** The human readable label of the expression */
    label: string;
    operations: FernApi.ExpressionOperationV2[];
    /** A short ID that can be used to reference the expression */
    reference: string;
    returns: FernApi.ReturnsMetaV2;
    /** The root reference for this expression (i.e. where the expression starts) */
    root_reference: string;
}
