// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface ExpressionFilterOptsPayloadV2 {
    /** The condition groups to apply in this filter. Only one group needs to be satisfied for the filter to pass. */
    condition_groups: FernApi.ConditionGroupPayloadV2[];
}
