// This file was auto-generated by Fern from our API Definition.

export interface ExpressionConcatenateOptsPayloadV2 {
    /** The reference that you want to concatenate with */
    reference: string;
}
