// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface ExpressionBranchPayloadV2 {
    /** When one of these condition groups are satisfied, this branch will be evaluated */
    condition_groups: IncidentIO.ConditionGroupPayloadV2[];
    result: IncidentIO.EngineParamBindingPayloadV2;
}
