// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface ExpressionBranchesOptsPayloadV2 {
    /** The branches to apply for this operation */
    branches: IncidentIO.ExpressionBranchPayloadV2[];
    returns: IncidentIO.ReturnsMetaV2;
}
