// This file was auto-generated by Fern from our API Definition.

export interface ExternalResourceV1 {
    /** ID of the resource in the external system */
    external_id: string;
    /** URL of the resource */
    permalink: string;
    /** E.g. PagerDuty: the external system that holds the resource */
    resource_type: ExternalResourceV1.ResourceType;
    /** Title of resource */
    title: string;
}

export namespace ExternalResourceV1 {
    /** E.g. PagerDuty: the external system that holds the resource */
    export const ResourceType = {
        PagerDutyIncident: "pager_duty_incident",
        OpsgenieAlert: "opsgenie_alert",
        DatadogMonitorAlert: "datadog_monitor_alert",
        GithubPullRequest: "github_pull_request",
        GitlabMergeRequest: "gitlab_merge_request",
        SentryIssue: "sentry_issue",
        JiraIssue: "jira_issue",
        JsmAlert: "jsm_alert",
        AtlassianStatuspageIncident: "atlassian_statuspage_incident",
        ZendeskTicket: "zendesk_ticket",
        GoogleCalendarEvent: "google_calendar_event",
        OutlookCalendarEvent: "outlook_calendar_event",
        SlackFile: "slack_file",
        Scrubbed: "scrubbed",
        StatuspageIncident: "statuspage_incident",
    } as const;
    export type ResourceType = (typeof ResourceType)[keyof typeof ResourceType];
}
