// This file was auto-generated by Fern from our API Definition.

export interface ExternalIssueReferenceV1 {
    /** Human readable ID for the issue */
    issue_name?: string;
    /** URL linking directly to the action in the issue tracker */
    issue_permalink?: string;
    /** ID of the issue tracker provider */
    provider?: ExternalIssueReferenceV1.Provider;
}

export namespace ExternalIssueReferenceV1 {
    /** ID of the issue tracker provider */
    export const Provider = {
        Asana: "asana",
        AzureDevops: "azure_devops",
        ClickUp: "click_up",
        Linear: "linear",
        Jira: "jira",
        JiraServer: "jira_server",
        Github: "github",
        Gitlab: "gitlab",
        ServiceNow: "service_now",
        Shortcut: "shortcut",
    } as const;
    export type Provider = (typeof Provider)[keyof typeof Provider];
}
