// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface IncidentMembershipsCreateResultV1 {
    incident_membership: IncidentIO.IncidentMembershipV1;
}
