// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface IncidentsListResultV2 {
    incidents: FernApi.IncidentV2[];
    pagination_meta?: FernApi.PaginationMetaResultWithTotalV2;
}
