// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface IncidentRoleAssignmentV2 {
    assignee?: IncidentIO.UserV2;
    role: IncidentIO.EmbeddedIncidentRoleV2;
}
