// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface IncidentUpdatesListResultV2 {
    incident_updates: IncidentIO.IncidentUpdateV2[];
    pagination_meta?: IncidentIO.PaginationMetaResultV2;
}
