// This file was auto-generated by Fern from our API Definition.

export interface IncidentTimestampV2 {
    /** Unique ID of this incident timestamp */
    id: string;
    /** Unique name of this timestamp */
    name: string;
    /** Order in which this timestamp should be shown */
    rank: number;
}
