// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface IncidentRolesUpdateResultV2 {
    incident_role: IncidentIO.IncidentRoleV2;
}
