// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface IncidentStatusesUpdateResultV1 {
    incident_status: IncidentIO.IncidentStatusV1;
}
