// This file was auto-generated by Fern from our API Definition.

export interface IncidentTypeV2 {
    /** Whether incidents of this must always, or can optionally, be created in triage */
    create_in_triage: IncidentTypeV2.CreateInTriage;
    /** When this resource was created */
    created_at: string;
    /** What is this incident type for? */
    description: string;
    /** Unique identifier for this Incident Type */
    id: string;
    /** The default Incident Type is used when no other type is explicitly specified */
    is_default: boolean;
    /** The name of this Incident Type */
    name: string;
    /** Should all incidents created with this Incident Type be private? */
    private_incidents_only: boolean;
    /** When this resource was last updated */
    updated_at: string;
}

export namespace IncidentTypeV2 {
    /** Whether incidents of this must always, or can optionally, be created in triage */
    export const CreateInTriage = {
        Always: "always",
        Optional: "optional",
    } as const;
    export type CreateInTriage = (typeof CreateInTriage)[keyof typeof CreateInTriage];
}
