// This file was auto-generated by Fern from our API Definition.

export interface IncidentTimestampValueV1 {
    /** When this last occurred, if it did */
    last_occurred_at?: string;
    /** Name of the lifecycle event */
    name: string;
}
