// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface IncidentMembershipV1 {
    /** When the membership was created */
    created_at: string;
    /** Unique identifier of this incident membership */
    id: string;
    /** Unique identifier of the incident */
    incident_id: string;
    /** When the membership was last updated */
    updated_at: string;
    user: IncidentIO.UserV1;
}
