// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface IncidentRolesShowResultV1 {
    incident_role: IncidentIO.IncidentRoleV1;
}
