// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface IncidentTypesListResultV1 {
    incident_types: FernApi.IncidentTypeV1[];
}
