// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface IncidentRoleAssignmentPayloadV2 {
    assignee?: FernApi.UserReferencePayloadV2;
    /** Unique ID of an incident role. Note that the 'reporter' role can only be assigned when creating an incident. */
    incident_role_id: string;
}
