// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface IncidentRolesListResultV2 {
    incident_roles: FernApi.IncidentRoleV2[];
}
