// This file was auto-generated by Fern from our API Definition.

export interface IncidentRelationshipDetailsV1 {
    /** External ID of this incident often prepended with 'INC-' */
    external_id: number;
    /** Unique identifier of this incident */
    id: string;
    /** Name of this incident */
    name: string;
}
