// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface IncidentRolesShowResultV2 {
    incident_role: FernApi.IncidentRoleV2;
}
