// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface IpAllowlistsUpdateIpAllowlistResultV1 {
    ip_allowlist: FernApi.IpAllowlistV1;
}
