// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface IpAllowlistV1 {
    /** A list of IP addresses or CIDR prefixes to allow */
    allowlist: IncidentIO.IpAllowlistItemV1[];
    /** Whether this IP allowlist is enabled or not */
    enabled: boolean;
    /** The time this allowlist was last updated */
    updated_at?: string;
    /** The version of this IP allowlist */
    version: number;
}
