// This file was auto-generated by Fern from our API Definition.

export interface PaginationMetaResultWithTotalV2 {
    /** If provided, pass this as the 'after' param to load the next page */
    after?: string;
    /** What was the maximum number of results requested */
    page_size: number;
    /** How many matching records were there in total, if known */
    total_record_count?: number;
}
