// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface SchedulesListScheduleEntriesResultV2 {
    pagination_meta?: FernApi.AfterPaginationMetaResultV2;
    schedule_entries: FernApi.ScheduleEntriesListPayloadV2;
}
