// This file was auto-generated by Fern from our API Definition.

export interface ScheduleLayerCreatePayloadV2 {
    /** Unique identifier of the layer */
    id?: string;
    /** Name of the layer */
    name: string;
}
