// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface ScheduleOverrideV2 {
    created_at: string;
    /** End of the override */
    end_at: string;
    /** Unique internal ID of the schedule override */
    id: string;
    /** The layer on the rotation on the schedule that this override applies to */
    layer_id: string;
    /** The rotation on the schedule that this override applies to */
    rotation_id: string;
    /** The schedule that this override applies to */
    schedule_id: string;
    /** Start of the override */
    start_at: string;
    updated_at: string;
    user?: FernApi.UserV2;
}
