// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface ScheduleCreatePayloadV2 {
    /** Annotations that can track metadata about the schedule */
    annotations?: Record<string, string>;
    config?: FernApi.ScheduleConfigCreatePayloadV2;
    holidays_public_config?: FernApi.ScheduleHolidaysPublicConfigPayloadV2;
    /** Name of the schedule */
    name?: string;
    /** IDs of teams that own this schedule */
    team_ids?: string[];
    /** Timezone of the schedule */
    timezone?: string;
}
