// This file was auto-generated by Fern from our API Definition.

export interface ScheduleHolidaysPublicConfigV2 {
    /** ISO 3166-1 alpha-2 country codes for the countries that this schedule is configured to view holidays for */
    country_codes: string[];
}
