// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface ScheduleEntriesListPayloadV2 {
    final: IncidentIO.ScheduleEntryV2[];
    overrides: IncidentIO.ScheduleEntryV2[];
    scheduled: IncidentIO.ScheduleEntryV2[];
}
