// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface StatusPagesListResponseIncidentsResultV1 {
    incidents: FernApi.StatusPageLinkedResponseIncidentV1[];
}
