// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface StatusPagesListResponseIncidentsResultV1 {
    incidents: IncidentIO.StatusPageLinkedResponseIncidentV1[];
}
