// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface UsersListResultV2 {
    pagination_meta: FernApi.PaginationMetaResultV2;
    users: FernApi.UserWithRolesV2[];
}
