// This file was auto-generated by Fern from our API Definition.

export interface WeekdayIntervalV2 {
    /** End time of the interval, in 24hr format */
    end_time: string;
    /** Start time of the interval, in 24hr format */
    start_time: string;
    /** Weekdays for use within a schedule or escalation path */
    weekday: WeekdayIntervalV2.Weekday;
}

export namespace WeekdayIntervalV2 {
    /** Weekdays for use within a schedule or escalation path */
    export const Weekday = {
        Monday: "monday",
        Tuesday: "tuesday",
        Wednesday: "wednesday",
        Thursday: "thursday",
        Friday: "friday",
        Saturday: "saturday",
        Sunday: "sunday",
    } as const;
    export type Weekday = (typeof Weekday)[keyof typeof Weekday];
}
