// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../index.js";

export interface WorkflowsCreateWorkflowResultV2 {
    management_meta: FernApi.ManagementMetaV2;
    workflow: FernApi.WorkflowV2;
}
