// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface WorkflowSlimV2 {
    /** Conditions that apply to the workflow trigger */
    condition_groups: IncidentIO.ConditionGroupV2[];
    /** Whether to continue executing the workflow if a step fails */
    continue_on_step_error: boolean;
    delay?: IncidentIO.WorkflowDelayV2;
    /** Expressions that make variables available in the scope */
    expressions: IncidentIO.ExpressionV2[];
    /** Folder to display the workflow in */
    folder?: string;
    /** Unique identifier for the workflow */
    id: string;
    /** Whether to include private escalations */
    include_private_escalations: boolean;
    /** Whether to include private incidents */
    include_private_incidents: boolean;
    /** Name provided by the user when creating the workflow */
    name: string;
    /** This workflow will run 'once for' a list of references */
    once_for: IncidentIO.EngineReferenceV2[];
    /** The time from which this workflow will run on incidents */
    runs_from?: string;
    /** Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents. */
    runs_on_incident_modes: WorkflowSlimV2.RunsOnIncidentModes.Item[];
    /** Which incidents should the workflow be applied to? */
    runs_on_incidents: WorkflowSlimV2.RunsOnIncidents;
    /** The shortform used to trigger this workflow (only applicable for manual triggers) */
    shortform?: string;
    /** What state this workflow is in */
    state: WorkflowSlimV2.State;
    /** Steps that are executed as part of the workflow */
    steps: IncidentIO.StepConfigSlimV2[];
    trigger: IncidentIO.TriggerSlimV2;
    /** Revision of the workflow, uniquely identifying it's version */
    version: number;
}

export namespace WorkflowSlimV2 {
    export type RunsOnIncidentModes = RunsOnIncidentModes.Item[];

    export namespace RunsOnIncidentModes {
        /** Incident mode that workflows can run on */
        export const Item = {
            Standard: "standard",
            Test: "test",
            Retrospective: "retrospective",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    /** Which incidents should the workflow be applied to? */
    export const RunsOnIncidents = {
        NewlyCreated: "newly_created",
        NewlyCreatedAndActive: "newly_created_and_active",
    } as const;
    export type RunsOnIncidents = (typeof RunsOnIncidents)[keyof typeof RunsOnIncidents];
    /** What state this workflow is in */
    export const State = {
        Active: "active",
        Disabled: "disabled",
        Draft: "draft",
        Error: "error",
    } as const;
    export type State = (typeof State)[keyof typeof State];
}
