// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../index.js";

export interface WorkflowsUpdateWorkflowResultV2 {
    management_meta: IncidentIO.ManagementMetaV2;
    workflow: IncidentIO.WorkflowV2;
}
