// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         incident_id: "01FCNDV6P870EA6S7TK1DSYD5H",
 *         page_size: 25,
 *         after: "01FDAG4SAP5TYPT98WGR2N7W91"
 *     }
 */
export interface IncidentRelationshipsV1ListRequest {
    /** ID of the incident to find relationships for */
    incident_id: string;
    /** Integer number of records to return */
    page_size?: number;
    /** An record's ID. This endpoint will return a list of records after this ID in relation to the API response order. */
    after?: string;
}
