// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../../../../index.js";

/**
 * @example
 *     {
 *         custom_field_entries: [{
 *                 custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *                 values: [{
 *                         id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *                         value_catalog_entry_id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *                         value_link: "https://google.com/",
 *                         value_numeric: "123.456",
 *                         value_option_id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *                         value_text: "This is my text field, I hope you like it",
 *                         value_timestamp: ""
 *                     }]
 *             }],
 *         idempotency_key: "alert-uuid",
 *         incident_role_assignments: [{
 *                 assignee: {
 *                     email: "bob@example.com",
 *                     id: "01G0J1EXE7AXZ2C93K61WBPYEH",
 *                     slack_user_id: "USER123"
 *                 },
 *                 incident_role_id: "01FH5TZRWMNAFB0DZ23FD1TV96"
 *             }],
 *         incident_type_id: "01FH5TZRWMNAFB0DZ23FD1TV96",
 *         mode: "real",
 *         name: "Our database is sad",
 *         severity_id: "01FH5TZRWMNAFB0DZ23FD1TV96",
 *         slack_team_id: "T02A1FSLE8J",
 *         source_message_channel_id: "C02AW36C1M5",
 *         source_message_timestamp: "1653650280.526509",
 *         status: "triage",
 *         summary: "Our database is really really sad, and we don't know why yet.",
 *         visibility: "public"
 *     }
 */
export interface IncidentsCreatePayloadV1 {
    /** Set the incident's custom fields to these values */
    custom_field_entries?: IncidentIO.CustomFieldEntryPayloadV1[];
    /** Unique string used to de-duplicate incident create requests */
    idempotency_key: string;
    /** Assign incident roles to these people */
    incident_role_assignments?: IncidentIO.IncidentRoleAssignmentPayloadV1[];
    /** Incident type to create this incident as */
    incident_type_id?: string;
    /** Whether the incident is real or test */
    mode?: IncidentsCreatePayloadV1.Mode;
    /** Explanation of the incident */
    name?: string;
    /** Severity to create incident as */
    severity_id?: string;
    /** ID of the Slack team / workspace. This is only required if you are using a Slack Enterprise Grid with multiple teams. */
    slack_team_id?: string;
    /** Channel ID of the source message, if this incident was created from one */
    source_message_channel_id?: string;
    /** Timestamp of the source message, if this incident was created from one */
    source_message_timestamp?: string;
    /** Current status of the incident */
    status?: IncidentsCreatePayloadV1.Status;
    /** Detailed description of the incident */
    summary?: string;
    /** Whether the incident should be open to anyone in your Slack workspace (public), or invite-only (private). For more information on Private Incidents see our [help centre](https://help.incident.io/articles/5905558102-can-we-mark-incidents-as-sensitive-and-restrict-access). */
    visibility: IncidentsCreatePayloadV1.Visibility;
}

export namespace IncidentsCreatePayloadV1 {
    /** Whether the incident is real or test */
    export const Mode = {
        Real: "real",
        Test: "test",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
    /** Current status of the incident */
    export const Status = {
        Triage: "triage",
        Investigating: "investigating",
        Fixing: "fixing",
        Monitoring: "monitoring",
        Closed: "closed",
        Declined: "declined",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Whether the incident should be open to anyone in your Slack workspace (public), or invite-only (private). For more information on Private Incidents see our [help centre](https://help.incident.io/articles/5905558102-can-we-mark-incidents-as-sensitive-and-restrict-access). */
    export const Visibility = {
        Public: "public",
        Private: "private",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
