// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         array: false,
 *         name: "service",
 *         required: false,
 *         type: "CatalogEntry[\"01GW2G3V0S59R238FAHPDS1R67\"]"
 *     }
 */
export interface AlertAttributesCreatePayloadV2 {
    /** Whether this attribute is an array */
    array: boolean;
    /** Unique name of this attribute */
    name: string;
    /** Whether this attribute is required. If this field is not set, the existing setting will be preserved. */
    required?: boolean;
    /** Engine resource name for this attribute */
    type: string;
}
