// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "01G0J1EXE7AXZ2C93K61WBPYEH"
 *     }
 */
export interface SchedulesV2DestroyRequest {
    /** Unique internal ID of the schedule */
    id: string;
}
