// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../../../../index.js";

/**
 * @example
 *     {
 *         end_at: "2021-08-17T14:00:00Z",
 *         layer_id: "01G0J1EXE7AXZ2C93K61WBPYNH",
 *         rotation_id: "01G0J1EXE7AXZ2C93K61WBPYEH",
 *         schedule_id: "01G0J1EXE7AXZ2C93K61WBPYEH",
 *         start_at: "2021-08-17T13:00:00Z",
 *         user: {
 *             email: "bob@example.com",
 *             id: "01G0J1EXE7AXZ2C93K61WBPYEH",
 *             slack_user_id: "USER123"
 *         }
 *     }
 */
export interface SchedulesCreateOverridePayloadV2 {
    /** End time of the override */
    end_at: string;
    /** The layer this override applies to */
    layer_id: string;
    /** The rotation this override applies to */
    rotation_id: string;
    /** The schedule this override applies to */
    schedule_id: string;
    /** Start time of the override */
    start_at: string;
    user: IncidentIO.UserReferencePayloadV2;
}
