// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         page_size: 25,
 *         after: "01FDAG4SAP5TYPT98WGR2N7W91"
 *     }
 */
export interface SchedulesV2ListRequest {
    /** Integer number of records to return */
    page_size?: number;
    /** A schedule's ID. This endpoint will return a list of schedules after this ID in relation to the API response order. */
    after?: string;
}
