// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         schedule_id: "01FDAG4SAP5TYPT98WGR2N7W91",
 *         entry_window_start: "2021-01-01T00:00:00Z",
 *         entry_window_end: "2021-01-01T00:00:00Z"
 *     }
 */
export interface SchedulesV2ListScheduleEntriesRequest {
    /** The ID of the schedule to get entries for. */
    schedule_id: string;
    /** The start of the window to get entries for. */
    entry_window_start?: string;
    /** The end of the window to get entries for. */
    entry_window_end?: string;
}
