// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         incident_id: "01G0J1EXE7AXZ2C93K61WBPYEH",
 *         page_size: 25,
 *         after: "01FDAG4SAP5TYPT98WGR2N7W91"
 *     }
 */
export interface IncidentUpdatesV2ListRequest {
    /** Incident whose updates you want to list */
    incident_id?: string;
    /** Integer number of records to return */
    page_size?: number;
    /** An record's ID. This endpoint will return a list of records after this ID in relation to the API response order. */
    after?: string;
}
