// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *         description: "The person currently coordinating the incident",
 *         instructions: "Take point on the incident; Make sure people are clear on responsibilities",
 *         name: "Incident Lead",
 *         required: false,
 *         shortform: "lead"
 *     }
 */
export interface IncidentRolesUpdatePayloadV1 {
    /** Unique identifier for the role */
    id: string;
    /** Describes the purpose of the role */
    description: string;
    /** Provided to whoever is nominated for the role. Note that this will be empty for the 'reporter' role. */
    instructions: string;
    /** Human readable name of the incident role */
    name: string;
    /** DEPRECATED: this will always be false. */
    required?: boolean;
    /** Short human readable name for Slack. Note that this will be empty for the 'reporter' role. */
    shortform: string;
}
