// This file was auto-generated by Fern from our API Definition.

import { IncidentIOClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ActionsV1Client", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new IncidentIOClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            actions: [
                {
                    assignee: {
                        email: "lisa@incident.io",
                        id: "01FCNDV6P870EA6S7TK1DSYDG0",
                        name: "Lisa Karlin Curtis",
                        role: "viewer",
                        slack_user_id: "U02AYNF2XJM",
                    },
                    completed_at: "2021-08-17T13:28:57Z",
                    created_at: "2021-08-17T13:28:57Z",
                    description: "Call the fire brigade",
                    external_issue_reference: {
                        issue_name: "INC-123",
                        issue_permalink: "https://linear.app/incident-io/issue/INC-1609/find-copywriter-to-write-up",
                        provider: "asana",
                    },
                    follow_up: true,
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    incident_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    status: "outstanding",
                    updated_at: "2021-08-17T13:28:57Z",
                },
            ],
        };
        server.mockEndpoint().get("/v1/actions").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.actionsV1.list({
            incident_id: "01FCNDV6P870EA6S7TK1DSYDG0",
            is_follow_up: true,
        });
        expect(response).toEqual({
            actions: [
                {
                    assignee: {
                        email: "lisa@incident.io",
                        id: "01FCNDV6P870EA6S7TK1DSYDG0",
                        name: "Lisa Karlin Curtis",
                        role: "viewer",
                        slack_user_id: "U02AYNF2XJM",
                    },
                    completed_at: "2021-08-17T13:28:57Z",
                    created_at: "2021-08-17T13:28:57Z",
                    description: "Call the fire brigade",
                    external_issue_reference: {
                        issue_name: "INC-123",
                        issue_permalink: "https://linear.app/incident-io/issue/INC-1609/find-copywriter-to-write-up",
                        provider: "asana",
                    },
                    follow_up: true,
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    incident_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    status: "outstanding",
                    updated_at: "2021-08-17T13:28:57Z",
                },
            ],
        });
    });

    test("show", async () => {
        const server = mockServerPool.createServer();
        const client = new IncidentIOClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            action: {
                assignee: {
                    email: "lisa@incident.io",
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    name: "Lisa Karlin Curtis",
                    role: "viewer",
                    slack_user_id: "U02AYNF2XJM",
                },
                completed_at: "2021-08-17T13:28:57Z",
                created_at: "2021-08-17T13:28:57Z",
                description: "Call the fire brigade",
                external_issue_reference: {
                    issue_name: "INC-123",
                    issue_permalink: "https://linear.app/incident-io/issue/INC-1609/find-copywriter-to-write-up",
                    provider: "asana",
                },
                follow_up: true,
                id: "01FCNDV6P870EA6S7TK1DSYDG0",
                incident_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                status: "outstanding",
                updated_at: "2021-08-17T13:28:57Z",
            },
        };
        server
            .mockEndpoint()
            .get("/v1/actions/01FCNDV6P870EA6S7TK1DSYDG0")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.actionsV1.show({
            id: "01FCNDV6P870EA6S7TK1DSYDG0",
        });
        expect(response).toEqual({
            action: {
                assignee: {
                    email: "lisa@incident.io",
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    name: "Lisa Karlin Curtis",
                    role: "viewer",
                    slack_user_id: "U02AYNF2XJM",
                },
                completed_at: "2021-08-17T13:28:57Z",
                created_at: "2021-08-17T13:28:57Z",
                description: "Call the fire brigade",
                external_issue_reference: {
                    issue_name: "INC-123",
                    issue_permalink: "https://linear.app/incident-io/issue/INC-1609/find-copywriter-to-write-up",
                    provider: "asana",
                },
                follow_up: true,
                id: "01FCNDV6P870EA6S7TK1DSYDG0",
                incident_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                status: "outstanding",
                updated_at: "2021-08-17T13:28:57Z",
            },
        });
    });
});
