// This file was auto-generated by Fern from our API Definition.

import { IncidentIOClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AlertEventsV2Client", () => {
    test("createhttp", async () => {
        const server = mockServerPool.createServer();
        const client = new IncidentIOClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {
            deduplication_key: "4293868629",
            description: "We've detected a number of timeouts on hello.world.com, the service may be down. To fix...",
            metadata: { service: "hello.world.com", team: ["my-team"] },
            source_url: "https://www.my-alerting-platform.com/alerts/my-alert-123",
            status: "firing",
            title: "*errors.withMessage: PG::Error failed to connect",
        };
        const rawResponseBody = {
            deduplication_key: "unique-key",
            message: "Event accepted for processing",
            status: "success",
        };
        server
            .mockEndpoint()
            .post("/v2/alert_events/http/01GW2G3V0S59R238FAHPDS1R66")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.alertEventsV2.createhttp({
            alert_source_config_id: "01GW2G3V0S59R238FAHPDS1R66",
            token: "some-random-string",
            deduplication_key: "4293868629",
            description: "We've detected a number of timeouts on hello.world.com, the service may be down. To fix...",
            metadata: {
                service: "hello.world.com",
                team: ["my-team"],
            },
            source_url: "https://www.my-alerting-platform.com/alerts/my-alert-123",
            status: "firing",
            title: "*errors.withMessage: PG::Error failed to connect",
        });
        expect(response).toEqual({
            deduplication_key: "unique-key",
            message: "Event accepted for processing",
            status: "success",
        });
    });
});
