// This file was auto-generated by Fern from our API Definition.

import { FernApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CustomFieldOptionsV1Client", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new FernApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            custom_field_options: [
                {
                    custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    sort_key: 10,
                    value: "Product",
                },
            ],
            pagination_meta: { after: "01FCNDV6P870EA6S7TK1DSYDG0", page_size: 25 },
        };
        server
            .mockEndpoint()
            .get("/v1/custom_field_options")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customFieldOptionsV1.list({
            page_size: 25,
            after: "01G0J1EXE7AXZ2C93K61WBPYEH",
            custom_field_id: "01FCNDV6P870EA6S7TK1DSYD5H",
        });
        expect(response).toEqual({
            custom_field_options: [
                {
                    custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    sort_key: 10,
                    value: "Product",
                },
            ],
            pagination_meta: {
                after: "01FCNDV6P870EA6S7TK1DSYDG0",
                page_size: 25,
            },
        });
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new FernApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0", sort_key: 10, value: "Product" };
        const rawResponseBody = {
            custom_field_option: {
                custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                id: "01FCNDV6P870EA6S7TK1DSYDG0",
                sort_key: 10,
                value: "Product",
            },
        };
        server
            .mockEndpoint()
            .post("/v1/custom_field_options")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customFieldOptionsV1.create({
            custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0",
            sort_key: 10,
            value: "Product",
        });
        expect(response).toEqual({
            custom_field_option: {
                custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                id: "01FCNDV6P870EA6S7TK1DSYDG0",
                sort_key: 10,
                value: "Product",
            },
        });
    });

    test("show", async () => {
        const server = mockServerPool.createServer();
        const client = new FernApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            custom_field_option: {
                custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                id: "01FCNDV6P870EA6S7TK1DSYDG0",
                sort_key: 10,
                value: "Product",
            },
        };
        server
            .mockEndpoint()
            .get("/v1/custom_field_options/01FCNDV6P870EA6S7TK1DSYDG0")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customFieldOptionsV1.show({
            id: "01FCNDV6P870EA6S7TK1DSYDG0",
        });
        expect(response).toEqual({
            custom_field_option: {
                custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                id: "01FCNDV6P870EA6S7TK1DSYDG0",
                sort_key: 10,
                value: "Product",
            },
        });
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new FernApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { sort_key: 10, value: "Product" };
        const rawResponseBody = {
            custom_field_option: {
                custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                id: "01FCNDV6P870EA6S7TK1DSYDG0",
                sort_key: 10,
                value: "Product",
            },
        };
        server
            .mockEndpoint()
            .put("/v1/custom_field_options/01FCNDV6P870EA6S7TK1DSYDG0")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customFieldOptionsV1.update({
            id: "01FCNDV6P870EA6S7TK1DSYDG0",
            sort_key: 10,
            value: "Product",
        });
        expect(response).toEqual({
            custom_field_option: {
                custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                id: "01FCNDV6P870EA6S7TK1DSYDG0",
                sort_key: 10,
                value: "Product",
            },
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new FernApiClient({ maxRetries: 0, environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/v1/custom_field_options/01FCNDV6P870EA6S7TK1DSYDG0")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.customFieldOptionsV1.delete({
            id: "01FCNDV6P870EA6S7TK1DSYDG0",
        });
        expect(response).toEqual(undefined);
    });
});
