// This file was auto-generated by Fern from our API Definition.

import { IncidentIOClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("FollowUpsV2Client", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new IncidentIOClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            follow_ups: [
                {
                    assignee: {
                        email: "lisa@incident.io",
                        id: "01FCNDV6P870EA6S7TK1DSYDG0",
                        name: "Lisa Karlin Curtis",
                        role: "viewer",
                        slack_user_id: "U02AYNF2XJM",
                    },
                    completed_at: "2021-08-17T13:28:57Z",
                    created_at: "2021-08-17T13:28:57Z",
                    creator: {
                        alert: {
                            id: "01GW2G3V0S59R238FAHPDS1R66",
                            title: "*errors.withMessage: PG::Error failed to connect",
                        },
                        api_key: { id: "01FCNDV6P870EA6S7TK1DSYDG0", name: "My test API key" },
                        user: {
                            email: "lisa@incident.io",
                            id: "01FCNDV6P870EA6S7TK1DSYDG0",
                            name: "Lisa Karlin Curtis",
                            role: "viewer",
                            slack_user_id: "U02AYNF2XJM",
                        },
                        workflow: { id: "01FCNDV6P870EA6S7TK1DSYDG0", name: "My little workflow" },
                    },
                    description: "Call the fire brigade",
                    external_issue_reference: {
                        issue_name: "INC-123",
                        issue_permalink: "https://linear.app/incident-io/issue/INC-1609/find-copywriter-to-write-up",
                        provider: "asana",
                    },
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    incident_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    labels: ["bug", "urgent"],
                    priority: {
                        description: "A follow-up that requires immediate attention.",
                        id: "01GNW4BAQ7XRMFF6FHKNXDFPRW",
                        name: "Urgent",
                        rank: 10,
                    },
                    status: "outstanding",
                    title: "Cat is stuck in the tree",
                    updated_at: "2021-08-17T13:28:57Z",
                },
            ],
        };
        server.mockEndpoint().get("/v2/follow_ups").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.followUpsV2.list({
            incident_id: "01FCNDV6P870EA6S7TK1DSYDG0",
        });
        expect(response).toEqual({
            follow_ups: [
                {
                    assignee: {
                        email: "lisa@incident.io",
                        id: "01FCNDV6P870EA6S7TK1DSYDG0",
                        name: "Lisa Karlin Curtis",
                        role: "viewer",
                        slack_user_id: "U02AYNF2XJM",
                    },
                    completed_at: "2021-08-17T13:28:57Z",
                    created_at: "2021-08-17T13:28:57Z",
                    creator: {
                        alert: {
                            id: "01GW2G3V0S59R238FAHPDS1R66",
                            title: "*errors.withMessage: PG::Error failed to connect",
                        },
                        api_key: {
                            id: "01FCNDV6P870EA6S7TK1DSYDG0",
                            name: "My test API key",
                        },
                        user: {
                            email: "lisa@incident.io",
                            id: "01FCNDV6P870EA6S7TK1DSYDG0",
                            name: "Lisa Karlin Curtis",
                            role: "viewer",
                            slack_user_id: "U02AYNF2XJM",
                        },
                        workflow: {
                            id: "01FCNDV6P870EA6S7TK1DSYDG0",
                            name: "My little workflow",
                        },
                    },
                    description: "Call the fire brigade",
                    external_issue_reference: {
                        issue_name: "INC-123",
                        issue_permalink: "https://linear.app/incident-io/issue/INC-1609/find-copywriter-to-write-up",
                        provider: "asana",
                    },
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    incident_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    labels: ["bug", "urgent"],
                    priority: {
                        description: "A follow-up that requires immediate attention.",
                        id: "01GNW4BAQ7XRMFF6FHKNXDFPRW",
                        name: "Urgent",
                        rank: 10,
                    },
                    status: "outstanding",
                    title: "Cat is stuck in the tree",
                    updated_at: "2021-08-17T13:28:57Z",
                },
            ],
        });
    });

    test("show", async () => {
        const server = mockServerPool.createServer();
        const client = new IncidentIOClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            follow_up: {
                assignee: {
                    email: "lisa@incident.io",
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    name: "Lisa Karlin Curtis",
                    role: "viewer",
                    slack_user_id: "U02AYNF2XJM",
                },
                completed_at: "2021-08-17T13:28:57Z",
                created_at: "2021-08-17T13:28:57Z",
                creator: {
                    alert: {
                        id: "01GW2G3V0S59R238FAHPDS1R66",
                        title: "*errors.withMessage: PG::Error failed to connect",
                    },
                    api_key: { id: "01FCNDV6P870EA6S7TK1DSYDG0", name: "My test API key" },
                    user: {
                        email: "lisa@incident.io",
                        id: "01FCNDV6P870EA6S7TK1DSYDG0",
                        name: "Lisa Karlin Curtis",
                        role: "viewer",
                        slack_user_id: "U02AYNF2XJM",
                    },
                    workflow: { id: "01FCNDV6P870EA6S7TK1DSYDG0", name: "My little workflow" },
                },
                description: "Call the fire brigade",
                external_issue_reference: {
                    issue_name: "INC-123",
                    issue_permalink: "https://linear.app/incident-io/issue/INC-1609/find-copywriter-to-write-up",
                    provider: "asana",
                },
                id: "01FCNDV6P870EA6S7TK1DSYDG0",
                incident_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                labels: ["bug", "urgent"],
                priority: {
                    description: "A follow-up that requires immediate attention.",
                    id: "01GNW4BAQ7XRMFF6FHKNXDFPRW",
                    name: "Urgent",
                    rank: 10,
                },
                status: "outstanding",
                title: "Cat is stuck in the tree",
                updated_at: "2021-08-17T13:28:57Z",
            },
        };
        server
            .mockEndpoint()
            .get("/v2/follow_ups/01FCNDV6P870EA6S7TK1DSYDG0")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.followUpsV2.show({
            id: "01FCNDV6P870EA6S7TK1DSYDG0",
        });
        expect(response).toEqual({
            follow_up: {
                assignee: {
                    email: "lisa@incident.io",
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    name: "Lisa Karlin Curtis",
                    role: "viewer",
                    slack_user_id: "U02AYNF2XJM",
                },
                completed_at: "2021-08-17T13:28:57Z",
                created_at: "2021-08-17T13:28:57Z",
                creator: {
                    alert: {
                        id: "01GW2G3V0S59R238FAHPDS1R66",
                        title: "*errors.withMessage: PG::Error failed to connect",
                    },
                    api_key: {
                        id: "01FCNDV6P870EA6S7TK1DSYDG0",
                        name: "My test API key",
                    },
                    user: {
                        email: "lisa@incident.io",
                        id: "01FCNDV6P870EA6S7TK1DSYDG0",
                        name: "Lisa Karlin Curtis",
                        role: "viewer",
                        slack_user_id: "U02AYNF2XJM",
                    },
                    workflow: {
                        id: "01FCNDV6P870EA6S7TK1DSYDG0",
                        name: "My little workflow",
                    },
                },
                description: "Call the fire brigade",
                external_issue_reference: {
                    issue_name: "INC-123",
                    issue_permalink: "https://linear.app/incident-io/issue/INC-1609/find-copywriter-to-write-up",
                    provider: "asana",
                },
                id: "01FCNDV6P870EA6S7TK1DSYDG0",
                incident_id: "01FCNDV6P870EA6S7TK1DSYDG0",
                labels: ["bug", "urgent"],
                priority: {
                    description: "A follow-up that requires immediate attention.",
                    id: "01GNW4BAQ7XRMFF6FHKNXDFPRW",
                    name: "Urgent",
                    rank: 10,
                },
                status: "outstanding",
                title: "Cat is stuck in the tree",
                updated_at: "2021-08-17T13:28:57Z",
            },
        });
    });
});
