// This file was auto-generated by Fern from our API Definition.

import { FernApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("IncidentTimestampsV2Client", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new FernApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            incident_timestamps: [{ id: "01FCNDV6P870EA6S7TK1DSYD5H", name: "Impact started", rank: 1 }],
        };
        server
            .mockEndpoint()
            .get("/v2/incident_timestamps")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.incidentTimestampsV2.list();
        expect(response).toEqual({
            incident_timestamps: [
                {
                    id: "01FCNDV6P870EA6S7TK1DSYD5H",
                    name: "Impact started",
                    rank: 1,
                },
            ],
        });
    });

    test("show", async () => {
        const server = mockServerPool.createServer();
        const client = new FernApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            incident_timestamp: { id: "01FCNDV6P870EA6S7TK1DSYD5H", name: "Impact started", rank: 1 },
        };
        server
            .mockEndpoint()
            .get("/v2/incident_timestamps/01FCNDV6P870EA6S7TK1DSYD5H")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.incidentTimestampsV2.show({
            id: "01FCNDV6P870EA6S7TK1DSYD5H",
        });
        expect(response).toEqual({
            incident_timestamp: {
                id: "01FCNDV6P870EA6S7TK1DSYD5H",
                name: "Impact started",
                rank: 1,
            },
        });
    });
});
