// This file was auto-generated by Fern from our API Definition.

import { IncidentIOClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("IncidentRelationshipsV1Client", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new IncidentIOClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            incident_relationships: [
                {
                    id: "01FCNDV6P870EA6S7TK1DSYD5H",
                    incident: { external_id: 123, id: "01FCNDV6P870EA6S7TK1DSYD5H", name: "The database is down" },
                },
            ],
            pagination_meta: { after: "01FCNDV6P870EA6S7TK1DSYDG0", page_size: 25 },
        };
        server
            .mockEndpoint()
            .get("/v1/incident_relationships")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.incidentRelationshipsV1.list({
            incident_id: "01FCNDV6P870EA6S7TK1DSYD5H",
            page_size: 25,
            after: "01FDAG4SAP5TYPT98WGR2N7W91",
        });
        expect(response).toEqual({
            incident_relationships: [
                {
                    id: "01FCNDV6P870EA6S7TK1DSYD5H",
                    incident: {
                        external_id: 123,
                        id: "01FCNDV6P870EA6S7TK1DSYD5H",
                        name: "The database is down",
                    },
                },
            ],
            pagination_meta: {
                after: "01FCNDV6P870EA6S7TK1DSYDG0",
                page_size: 25,
            },
        });
    });
});
