// This file was auto-generated by Fern from our API Definition.

import { FernApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UsersV2Client", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new FernApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            pagination_meta: { after: "01FCNDV6P870EA6S7TK1DSYDG0", page_size: 25 },
            users: [
                {
                    base_role: {
                        description: "Elevated permissions for the customer success team.",
                        id: "01FCNDV6P870EA6S7TK1DSYDG0",
                        name: "Customer Success",
                        slug: "customer-success",
                    },
                    custom_roles: [
                        {
                            description: "Elevated permissions for the customer success team.",
                            id: "01FCNDV6P870EA6S7TK1DSYDG0",
                            name: "Customer Success",
                            slug: "customer-success",
                        },
                    ],
                    email: "lisa@incident.io",
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    name: "Lisa Karlin Curtis",
                    role: "viewer",
                    slack_user_id: "U02AYNF2XJM",
                },
            ],
        };
        server.mockEndpoint().get("/v2/users").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.usersV2.list({
            email: "john.doe@incident.io",
            slack_user_id: "U12345678",
            page_size: 25,
            after: "01FDAG4SAP5TYPT98WGR2N7W91",
        });
        expect(response).toEqual({
            pagination_meta: {
                after: "01FCNDV6P870EA6S7TK1DSYDG0",
                page_size: 25,
            },
            users: [
                {
                    base_role: {
                        description: "Elevated permissions for the customer success team.",
                        id: "01FCNDV6P870EA6S7TK1DSYDG0",
                        name: "Customer Success",
                        slug: "customer-success",
                    },
                    custom_roles: [
                        {
                            description: "Elevated permissions for the customer success team.",
                            id: "01FCNDV6P870EA6S7TK1DSYDG0",
                            name: "Customer Success",
                            slug: "customer-success",
                        },
                    ],
                    email: "lisa@incident.io",
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    name: "Lisa Karlin Curtis",
                    role: "viewer",
                    slack_user_id: "U02AYNF2XJM",
                },
            ],
        });
    });

    test("show", async () => {
        const server = mockServerPool.createServer();
        const client = new FernApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            user: {
                base_role: {
                    description: "Elevated permissions for the customer success team.",
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    name: "Customer Success",
                    slug: "customer-success",
                },
                custom_roles: [
                    {
                        description: "Elevated permissions for the customer success team.",
                        id: "01FCNDV6P870EA6S7TK1DSYDG0",
                        name: "Customer Success",
                        slug: "customer-success",
                    },
                ],
                email: "lisa@incident.io",
                id: "01FCNDV6P870EA6S7TK1DSYDG0",
                name: "Lisa Karlin Curtis",
                role: "viewer",
                slack_user_id: "U02AYNF2XJM",
            },
        };
        server
            .mockEndpoint()
            .get("/v2/users/01FCNDV6P870EA6S7TK1DSYDG0")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.usersV2.show({
            id: "01FCNDV6P870EA6S7TK1DSYDG0",
        });
        expect(response).toEqual({
            user: {
                base_role: {
                    description: "Elevated permissions for the customer success team.",
                    id: "01FCNDV6P870EA6S7TK1DSYDG0",
                    name: "Customer Success",
                    slug: "customer-success",
                },
                custom_roles: [
                    {
                        description: "Elevated permissions for the customer success team.",
                        id: "01FCNDV6P870EA6S7TK1DSYDG0",
                        name: "Customer Success",
                        slug: "customer-success",
                    },
                ],
                email: "lisa@incident.io",
                id: "01FCNDV6P870EA6S7TK1DSYDG0",
                name: "Lisa Karlin Curtis",
                role: "viewer",
                slack_user_id: "U02AYNF2XJM",
            },
        });
    });
});
