// This file was auto-generated by Fern from our API Definition.

import { FernApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UtilitiesV1Client", () => {
    test("identity", async () => {
        const server = mockServerPool.createServer();
        const client = new FernApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            identity: {
                dashboard_url: "https://app.incident.io/my-org",
                name: "Alertmanager token",
                roles: ["viewer"],
            },
        };
        server.mockEndpoint().get("/v1/identity").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.utilitiesV1.identity();
        expect(response).toEqual({
            identity: {
                dashboard_url: "https://app.incident.io/my-org",
                name: "Alertmanager token",
                roles: ["viewer"],
            },
        });
    });
});
