// This file was auto-generated by Fern from our API Definition.

export const IncidentIOEnvironment = {
    Default: "https://api.incident.io",
} as const;

export type IncidentIOEnvironment = typeof IncidentIOEnvironment.Default;
