// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "01GW2G3V0S59R238FAHPDS1R66"
 *     }
 */
export interface AlertSourcesV2DeleteRequest {
    /** The ID of this alert source */
    id: string;
}
