// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "01GW2G3V0S59R238FAHPDS1R66",
 *         http_custom_options: {
 *             deduplication_key_path: "$.alert_id",
 *             transform_expression: "return {\n  title: $.title || $.name || 'Unknown Alert',\n  status: $.status === 'resolved' ? 'resolved' : 'firing',\n  description: $.description || $.message || '',\n  sourceURL: $.url || $.link || '',\n  metadata: { team: $.team, severity: $.severity }\n}"
 *         },
 *         jira_options: {
 *             project_ids: ["01GBSQF3FHF7FWZQNWGHAVQ804", "10043"]
 *         },
 *         name: "Production Web Dashboard Alerts",
 *         owning_team_ids: ["01G0J1EXE7AXZ2C93K61WBPYEH"],
 *         template: {
 *             attributes: [{
 *                     alert_attribute_id: "abc123",
 *                     binding: {
 *                         array_value: [{
 *                                 literal: "SEV123",
 *                                 reference: "incident.severity"
 *                             }],
 *                         value: {
 *                             literal: "SEV123",
 *                             reference: "incident.severity"
 *                         }
 *                     }
 *                 }],
 *             description: {
 *                 literal: "SEV123",
 *                 reference: "incident.severity"
 *             },
 *             expressions: [{
 *                     else_branch: {
 *                         result: {
 *                             array_value: [{
 *                                     literal: "SEV123",
 *                                     reference: "incident.severity"
 *                                 }],
 *                             value: {
 *                                 literal: "SEV123",
 *                                 reference: "incident.severity"
 *                             }
 *                         }
 *                     },
 *                     label: "Team Slack channel",
 *                     operations: [{
 *                             branches: {
 *                                 branches: [{
 *                                         condition_groups: [{
 *                                                 conditions: [{
 *                                                         operation: "one_of",
 *                                                         param_bindings: [{
 *                                                                 array_value: [{
 *                                                                         literal: "SEV123",
 *                                                                         reference: "incident.severity"
 *                                                                     }],
 *                                                                 value: {
 *                                                                     literal: "SEV123",
 *                                                                     reference: "incident.severity"
 *                                                                 }
 *                                                             }],
 *                                                         subject: "incident.severity"
 *                                                     }]
 *                                             }],
 *                                         result: {
 *                                             array_value: [{
 *                                                     literal: "SEV123",
 *                                                     reference: "incident.severity"
 *                                                 }],
 *                                             value: {
 *                                                 literal: "SEV123",
 *                                                 reference: "incident.severity"
 *                                             }
 *                                         }
 *                                     }],
 *                                 returns: {
 *                                     array: true,
 *                                     type: "IncidentStatus"
 *                                 }
 *                             },
 *                             concatenate: {
 *                                 reference: "catalog_attribute[\"01FCNDV6P870EA6S7TK1DSYD5H\"]"
 *                             },
 *                             filter: {
 *                                 condition_groups: [{
 *                                         conditions: [{
 *                                                 operation: "one_of",
 *                                                 param_bindings: [{
 *                                                         array_value: [{
 *                                                                 literal: "SEV123",
 *                                                                 reference: "incident.severity"
 *                                                             }],
 *                                                         value: {
 *                                                             literal: "SEV123",
 *                                                             reference: "incident.severity"
 *                                                         }
 *                                                     }],
 *                                                 subject: "incident.severity"
 *                                             }]
 *                                     }]
 *                             },
 *                             navigate: {
 *                                 reference: "catalog_attribute[\"01FCNDV6P870EA6S7TK1DSYD5H\"]"
 *                             },
 *                             operation_type: "navigate",
 *                             parse: {
 *                                 returns: {
 *                                     array: true,
 *                                     type: "IncidentStatus"
 *                                 },
 *                                 source: "metadata.annotations[\"github.com/repo\"]"
 *                             }
 *                         }],
 *                     reference: "abc123",
 *                     root_reference: "incident.status"
 *                 }],
 *             is_private: false,
 *             title: {
 *                 literal: "SEV123",
 *                 reference: "incident.severity"
 *             },
 *             visible_to_teams: {
 *                 array_value: [{
 *                         literal: "SEV123",
 *                         reference: "incident.severity"
 *                     }],
 *                 value: {
 *                     literal: "SEV123",
 *                     reference: "incident.severity"
 *                 }
 *             }
 *         }
 *     }
 */
export interface AlertSourcesUpdatePayloadV2 {
    /** The ID of this alert source */
    id: string;
    http_custom_options?: IncidentIO.AlertSourceHttpCustomOptionsV2;
    jira_options?: IncidentIO.AlertSourceJiraOptionsV2;
    /** Unique name of the alert source */
    name: string;
    /** IDs of teams that own this alert source */
    owning_team_ids?: string[];
    template: IncidentIO.AlertTemplatePayloadV2;
}
