// This file was auto-generated by Fern from our API Definition.

/** Filter to follow-ups from incidents of the given mode. If not set, only follow-ups from `standard` and `retrospective` incidents are returned */
export const FollowUpsV2ListRequestIncidentMode = {
    Standard: "standard",
    Retrospective: "retrospective",
    Test: "test",
    Tutorial: "tutorial",
    Stream: "stream",
} as const;
export type FollowUpsV2ListRequestIncidentMode =
    (typeof FollowUpsV2ListRequestIncidentMode)[keyof typeof FollowUpsV2ListRequestIncidentMode];
