// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "01FDAG4SAP5TYPT98WGR2N7W91"
 *     }
 */
export interface IncidentsV2ShowRequest {
    /** Unique identifier for the incident */
    id: string;
}
