// This file was auto-generated by Fern from our API Definition.

import type * as IncidentIO from "../../../../index.js";

/**
 * @example
 *     {
 *         custom_field_entries: [{
 *                 custom_field_id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *                 values: [{
 *                         id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *                         value_catalog_entry_id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *                         value_link: "https://google.com/",
 *                         value_numeric: "123.456",
 *                         value_option_id: "01FCNDV6P870EA6S7TK1DSYDG0",
 *                         value_text: "This is my text field, I hope you like it",
 *                         value_timestamp: ""
 *                     }]
 *             }],
 *         idempotency_key: "alert-uuid",
 *         incident_role_assignments: [{
 *                 assignee: {
 *                     email: "bob@example.com",
 *                     id: "01G0J1EXE7AXZ2C93K61WBPYEH",
 *                     slack_user_id: "USER123"
 *                 },
 *                 incident_role_id: "01FH5TZRWMNAFB0DZ23FD1TV96"
 *             }],
 *         incident_status_id: "01G0J1EXE7AXZ2C93K61WBPYEH",
 *         incident_timestamp_values: [{
 *                 incident_timestamp_id: "01FCNDV6P870EA6S7TK1DSYD5H",
 *                 value: "2021-08-17T13:28:57Z"
 *             }],
 *         incident_type_id: "01FH5TZRWMNAFB0DZ23FD1TV96",
 *         mode: "standard",
 *         name: "Our database is sad",
 *         retrospective_incident_options: {
 *             external_id: 123,
 *             postmortem_document_url: "https://docs.google.com/my_doc_id",
 *             slack_channel_id: "abc123"
 *         },
 *         severity_id: "01FH5TZRWMNAFB0DZ23FD1TV96",
 *         slack_channel_name_override: "inc-123-database-down",
 *         slack_team_id: "T02A1FSLE8J",
 *         summary: "Our database is really really sad, and we don't know why yet.",
 *         visibility: "public"
 *     }
 */
export interface IncidentsCreatePayloadV2 {
    /** Set the incident's custom fields to these values */
    custom_field_entries?: IncidentIO.CustomFieldEntryPayloadV2[];
    /** Unique string used to de-duplicate incident create requests */
    idempotency_key: string;
    /** Assign incident roles to these people */
    incident_role_assignments?: IncidentIO.IncidentRoleAssignmentPayloadV2[];
    /** Incident status to assign to the incident */
    incident_status_id?: string;
    /** Assign the incident's timestamps to these values */
    incident_timestamp_values?: IncidentIO.IncidentTimestampValuePayloadV2[];
    /** Incident type to create this incident as */
    incident_type_id?: string;
    /** Whether the incident is real, a test, a tutorial, or importing as a retrospective incident */
    mode?: IncidentsCreatePayloadV2.Mode;
    /** Explanation of the incident */
    name?: string;
    retrospective_incident_options?: IncidentIO.RetrospectiveIncidentOptionsV2;
    /** Severity to create incident as */
    severity_id?: string;
    /** Name of the Slack channel to create for this incident */
    slack_channel_name_override?: string;
    /** Slack Team to create the incident in */
    slack_team_id?: string;
    /** Detailed description of the incident */
    summary?: string;
    /** Whether the incident should be open to anyone in your Slack workspace (public), or invite-only (private). For more information on Private Incidents see our [help centre](https://help.incident.io/articles/5905558102-can-we-mark-incidents-as-sensitive-and-restrict-access). */
    visibility: IncidentsCreatePayloadV2.Visibility;
}

export namespace IncidentsCreatePayloadV2 {
    /** Whether the incident is real, a test, a tutorial, or importing as a retrospective incident */
    export const Mode = {
        Standard: "standard",
        Retrospective: "retrospective",
        Test: "test",
        Tutorial: "tutorial",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
    /** Whether the incident should be open to anyone in your Slack workspace (public), or invite-only (private). For more information on Private Incidents see our [help centre](https://help.incident.io/articles/5905558102-can-we-mark-incidents-as-sensitive-and-restrict-access). */
    export const Visibility = {
        Public: "public",
        Private: "private",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
