// This file was auto-generated by Fern from our API Definition.

import type * as FernApi from "../../../../index.js";

/**
 * @example
 *     {
 *         page_size: 25,
 *         after: "01FDAG4SAP5TYPT98WGR2N7W91"
 *     }
 */
export interface IncidentsV2ListRequest {
    /** Integer number of records to return */
    page_size?: number;
    /** An incident's ID. This endpoint will return a list of incidents after this ID in relation to the API response order. */
    after?: string;
    /** How to combine the filters: 'all' combines them with AND logic (all must match), 'any' combines them with OR logic (any can match). Defaults to 'all'. */
    filter_mode?: FernApi.IncidentsV2ListRequestFilterMode;
    /** Filter on incident status. The accepted operators are 'one_of', or 'not_in'. */
    status?: Record<string, string[]>;
    /** Filter on the category of the incidents status. The accepted operators are 'one_of', or 'not_in'. */
    status_category?: Record<string, string[]>;
    /** Filter on incident created at timestamp. The accepted operators are 'gte', 'lte' and 'date_range'. */
    created_at?: Record<string, string[]>;
    /** Filter on incident updated at timestamp. The accepted operators are 'gte', 'lte' and 'date_range'. */
    updated_at?: Record<string, string[]>;
    /** Filter on incident severity. The accepted operators are 'one_of', 'not_in', 'gte', 'lte'. */
    severity?: Record<string, string[]>;
    /** Filter on incident type. The accepted operators are 'one_of, or 'not_in'. */
    incident_type?: Record<string, string[]>;
    /** Filter on an incident role. Role ID should be sent, followed by the operator and values. The accepted operators are 'one_of', 'is_blank'. */
    incident_role?: Record<string, Record<string, string[]>>;
    /** Filter on an incident custom field. Custom field ID should be sent, followed by the operator and values. Accepted operator will depend on the custom field type. */
    custom_field?: Record<string, Record<string, string[]>>;
    /** Filter on incident mode. The accepted operator is 'one_of'.  If this is not provided, this value defaults to `{"one_of": ["standard", "retrospective"] }`, meaning that test and tutorial incidents are not included. */
    mode?: Record<string, string[]>;
}
